---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/nginx"
  github_url: "https://github.com/debops/ansible-nginx"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:

    - name:  'Maciej Delmanowski'
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

    - name:  'Robin Schneider'
      email: 'ypid@riseup.net'
      github: 'ypid'

  synopsis: |
    [Nginx](https://nginx.org/) is a fast and light webserver with extensible
    configuration.

    The `debops.nginx` role can be used to install and manage `nginx` configuration
    for multiple websites at the same time. The server is configured using
    inventory variables. This role can also be used as a dependency of another role
    to configure a webserver for that role using dependency variables.
