---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/apt_proxy"
  github_url: "https://github.com/debops/ansible-apt_proxy"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

    - name:  'Robin Schneider'
      email: 'ypid@riseup.net'
      github: 'ypid'

  synopsis: |
    This role manages the HTTP/HTTPS/FTP proxy configuration for APT. You can
    define what proxy to use, what hosts should be connected to directly, as well
    as set additional APT configuration options related to proxies as needed.

    The role also features proxy online detection support to silently
    skip/ignore temporally offline proxies which can make sense for
    workstations and home servers.
