image: python:alpine3.6

pages:
  script:
  - pip install sphinx
  - apk --no-cache add make
  - cd docs
  - make html
  - mv _build/html ../public
  artifacts:
    paths:
    - public
  only:
  - master
