---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible/com/debops/salt"
  github_url: "https://github.com/debops/ansible-salt"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    The `debops.salt` Ansible role can be used to install and configure
    [SaltStack](https://saltstack.com/) Master service. It is expected that Salt
    Minions are installed using host deployment methods like PXE/preseeding, LXC
    template scripts, etc. and contact the Salt Master service over DNS.
