[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "distributionPackage"
author = "Russell Smiley"
author-email = "im.russell.smiley@gmail.com"
home-page = "https://gitlab.com/blueskyjunkie/distribution-package"
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
requires = [ "packageManifest" ]
description-file = "README.rst"
keywords = "manifest package distribution file"
requires-python = ">=3"

[tool.flit.scripts]
makePackage = "distributionPackage:main"
