# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_webtree_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1150, 842)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_21.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_21.setSpacing(8)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.GRP_WORKFLOW = QtWidgets.QGroupBox(self.frame)
        self.GRP_WORKFLOW.setObjectName("GRP_WORKFLOW")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.GRP_WORKFLOW)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BTN_WORKFLOW = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_WORKFLOW.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_WORKFLOW.setMaximumSize(QtCore.QSize(64, 64))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/intermake/dropdown.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_WORKFLOW.setIcon(icon)
        self.BTN_WORKFLOW.setIconSize(QtCore.QSize(32, 32))
        self.BTN_WORKFLOW.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_WORKFLOW.setObjectName("BTN_WORKFLOW")
        self.horizontalLayout_2.addWidget(self.BTN_WORKFLOW)
        self.line_2 = QtWidgets.QFrame(self.GRP_WORKFLOW)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.BTN_CREATE = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_CREATE.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_CREATE.setMaximumSize(QtCore.QSize(64, 64))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/groot/create.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_CREATE.setIcon(icon1)
        self.BTN_CREATE.setIconSize(QtCore.QSize(32, 32))
        self.BTN_CREATE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_CREATE.setObjectName("BTN_CREATE")
        self.horizontalLayout_2.addWidget(self.BTN_CREATE)
        self.BTN_REMOVE = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_REMOVE.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_REMOVE.setMaximumSize(QtCore.QSize(64, 64))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/groot/remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_REMOVE.setIcon(icon2)
        self.BTN_REMOVE.setIconSize(QtCore.QSize(32, 32))
        self.BTN_REMOVE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_REMOVE.setObjectName("BTN_REMOVE")
        self.horizontalLayout_2.addWidget(self.BTN_REMOVE)
        self.BTN_VIEW = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_VIEW.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_VIEW.setMaximumSize(QtCore.QSize(64, 64))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/groot/view.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_VIEW.setIcon(icon3)
        self.BTN_VIEW.setIconSize(QtCore.QSize(32, 32))
        self.BTN_VIEW.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_VIEW.setObjectName("BTN_VIEW")
        self.horizontalLayout_2.addWidget(self.BTN_VIEW)
        self.horizontalLayout_21.addWidget(self.GRP_WORKFLOW)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BTN_SELECTION = QtWidgets.QToolButton(self.groupBox)
        self.BTN_SELECTION.setMinimumSize(QtCore.QSize(192, 64))
        self.BTN_SELECTION.setMaximumSize(QtCore.QSize(192, 64))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/groot/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SELECTION.setIcon(icon4)
        self.BTN_SELECTION.setIconSize(QtCore.QSize(32, 32))
        self.BTN_SELECTION.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.BTN_SELECTION.setObjectName("BTN_SELECTION")
        self.horizontalLayout.addWidget(self.BTN_SELECTION)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.BTN_SYSTEM_BROWSER = QtWidgets.QToolButton(self.groupBox)
        self.BTN_SYSTEM_BROWSER.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_SYSTEM_BROWSER.setMaximumSize(QtCore.QSize(64, 64))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/groot/external.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SYSTEM_BROWSER.setIcon(icon5)
        self.BTN_SYSTEM_BROWSER.setIconSize(QtCore.QSize(32, 32))
        self.BTN_SYSTEM_BROWSER.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_SYSTEM_BROWSER.setObjectName("BTN_SYSTEM_BROWSER")
        self.horizontalLayout.addWidget(self.BTN_SYSTEM_BROWSER)
        self.BTN_BROWSE_HERE = QtWidgets.QToolButton(self.groupBox)
        self.BTN_BROWSE_HERE.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_BROWSE_HERE.setMaximumSize(QtCore.QSize(64, 64))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/groot/internal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_BROWSE_HERE.setIcon(icon6)
        self.BTN_BROWSE_HERE.setIconSize(QtCore.QSize(32, 32))
        self.BTN_BROWSE_HERE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_BROWSE_HERE.setObjectName("BTN_BROWSE_HERE")
        self.horizontalLayout.addWidget(self.BTN_BROWSE_HERE)
        self.BTN_SAVE_TO_FILE = QtWidgets.QToolButton(self.groupBox)
        self.BTN_SAVE_TO_FILE.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_SAVE_TO_FILE.setMaximumSize(QtCore.QSize(64, 64))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/groot/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SAVE_TO_FILE.setIcon(icon7)
        self.BTN_SAVE_TO_FILE.setIconSize(QtCore.QSize(32, 32))
        self.BTN_SAVE_TO_FILE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_SAVE_TO_FILE.setObjectName("BTN_SAVE_TO_FILE")
        self.horizontalLayout.addWidget(self.BTN_SAVE_TO_FILE)
        self.horizontalLayout_21.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.LBL_NO_TREES_WARNING = QtWidgets.QLabel(Dialog)
        self.LBL_NO_TREES_WARNING.setObjectName("LBL_NO_TREES_WARNING")
        self.verticalLayout.addWidget(self.LBL_NO_TREES_WARNING)
        self.LBL_SELECTION_WARNING = QtWidgets.QLabel(Dialog)
        self.LBL_SELECTION_WARNING.setObjectName("LBL_SELECTION_WARNING")
        self.verticalLayout.addWidget(self.LBL_SELECTION_WARNING)
        self.LBL_TITLE = QtWidgets.QLabel(Dialog)
        self.LBL_TITLE.setObjectName("LBL_TITLE")
        self.verticalLayout.addWidget(self.LBL_TITLE)
        self.WIDGET_OTHER = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WIDGET_OTHER.sizePolicy().hasHeightForWidth())
        self.WIDGET_OTHER.setSizePolicy(sizePolicy)
        self.WIDGET_OTHER.setObjectName("WIDGET_OTHER")
        self.gridLayout = QtWidgets.QGridLayout(self.WIDGET_OTHER)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.LBL_NO_INBUILT = QtWidgets.QLabel(self.WIDGET_OTHER)
        self.LBL_NO_INBUILT.setAlignment(QtCore.Qt.AlignCenter)
        self.LBL_NO_INBUILT.setObjectName("LBL_NO_INBUILT")
        self.gridLayout.addWidget(self.LBL_NO_INBUILT, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.WIDGET_OTHER)
        self.WIDGET_MAIN = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WIDGET_MAIN.sizePolicy().hasHeightForWidth())
        self.WIDGET_MAIN.setSizePolicy(sizePolicy)
        self.WIDGET_MAIN.setObjectName("WIDGET_MAIN")
        self.verticalLayout.addWidget(self.WIDGET_MAIN)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.GRP_WORKFLOW.setTitle(_translate("Dialog", "Workflow"))
        self.BTN_WORKFLOW.setText(_translate("Dialog", "Workflow"))
        self.BTN_CREATE.setText(_translate("Dialog", "Create"))
        self.BTN_REMOVE.setText(_translate("Dialog", "Remove"))
        self.BTN_VIEW.setText(_translate("Dialog", "View"))
        self.groupBox.setTitle(_translate("Dialog", "Viewer"))
        self.BTN_SELECTION.setText(_translate("Dialog", "Selection"))
        self.BTN_SYSTEM_BROWSER.setText(_translate("Dialog", "System\n"
"browser"))
        self.BTN_BROWSE_HERE.setText(_translate("Dialog", "View\n"
"here"))
        self.BTN_SAVE_TO_FILE.setText(_translate("Dialog", "Save"))
        self.LBL_NO_TREES_WARNING.setText(_translate("Dialog", "You have no trees or graphs, go to the <a href=\"action:view_workflow\">workflow</a>."))
        self.LBL_NO_TREES_WARNING.setProperty("style", _translate("Dialog", "warning"))
        self.LBL_SELECTION_WARNING.setText(_translate("Dialog", "There are no trees in the <a href=\"action:view_entities\">current selection</a>."))
        self.LBL_SELECTION_WARNING.setProperty("style", _translate("Dialog", "warning"))
        self.LBL_TITLE.setText(_translate("Dialog", "TextLabel"))
        self.LBL_TITLE.setProperty("style", _translate("Dialog", "title"))
        self.LBL_NO_INBUILT.setText(_translate("Dialog", "<p>The inbuilt browser has been turned off in the <a href=\"action:view_options\">settings</a>.</p>\n"
"<p>Either <a href=\"action:enable_inbuilt_browser\">enable</a> the inbuilt browser or use the external browser.</p>"))


