# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_lego_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1071, 864)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_23.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_23.setSpacing(8)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.GRP_WORKFLOW = QtWidgets.QGroupBox(self.frame)
        self.GRP_WORKFLOW.setObjectName("GRP_WORKFLOW")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.GRP_WORKFLOW)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BTN_WORKFLOW = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_WORKFLOW.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_WORKFLOW.setMaximumSize(QtCore.QSize(64, 64))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/intermake/dropdown.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_WORKFLOW.setIcon(icon)
        self.BTN_WORKFLOW.setIconSize(QtCore.QSize(32, 32))
        self.BTN_WORKFLOW.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_WORKFLOW.setObjectName("BTN_WORKFLOW")
        self.horizontalLayout.addWidget(self.BTN_WORKFLOW)
        self.line_3 = QtWidgets.QFrame(self.GRP_WORKFLOW)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.BTN_CREATE = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_CREATE.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_CREATE.setMaximumSize(QtCore.QSize(64, 64))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/groot/create.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_CREATE.setIcon(icon1)
        self.BTN_CREATE.setIconSize(QtCore.QSize(32, 32))
        self.BTN_CREATE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_CREATE.setObjectName("BTN_CREATE")
        self.horizontalLayout.addWidget(self.BTN_CREATE)
        self.BTN_REMOVE = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_REMOVE.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_REMOVE.setMaximumSize(QtCore.QSize(64, 64))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/groot/remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_REMOVE.setIcon(icon2)
        self.BTN_REMOVE.setIconSize(QtCore.QSize(32, 32))
        self.BTN_REMOVE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_REMOVE.setObjectName("BTN_REMOVE")
        self.horizontalLayout.addWidget(self.BTN_REMOVE)
        self.BTN_VIEW = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_VIEW.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_VIEW.setMaximumSize(QtCore.QSize(64, 64))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/groot/view.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_VIEW.setIcon(icon3)
        self.BTN_VIEW.setIconSize(QtCore.QSize(32, 32))
        self.BTN_VIEW.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_VIEW.setObjectName("BTN_VIEW")
        self.horizontalLayout.addWidget(self.BTN_VIEW)
        self.horizontalLayout_23.addWidget(self.GRP_WORKFLOW)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BTN_CHANGE_SELECTION = QtWidgets.QToolButton(self.groupBox_2)
        self.BTN_CHANGE_SELECTION.setMinimumSize(QtCore.QSize(192, 64))
        self.BTN_CHANGE_SELECTION.setMaximumSize(QtCore.QSize(192, 64))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/groot/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_CHANGE_SELECTION.setIcon(icon4)
        self.BTN_CHANGE_SELECTION.setIconSize(QtCore.QSize(32, 32))
        self.BTN_CHANGE_SELECTION.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.BTN_CHANGE_SELECTION.setObjectName("BTN_CHANGE_SELECTION")
        self.horizontalLayout_2.addWidget(self.BTN_CHANGE_SELECTION)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.BTN_REFRESH = QtWidgets.QToolButton(self.groupBox_2)
        self.BTN_REFRESH.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_REFRESH.setMaximumSize(QtCore.QSize(64, 64))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/groot/refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_REFRESH.setIcon(icon5)
        self.BTN_REFRESH.setIconSize(QtCore.QSize(32, 32))
        self.BTN_REFRESH.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_REFRESH.setObjectName("BTN_REFRESH")
        self.horizontalLayout_2.addWidget(self.BTN_REFRESH)
        self.BTN_ALIGN = QtWidgets.QToolButton(self.groupBox_2)
        self.BTN_ALIGN.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_ALIGN.setMaximumSize(QtCore.QSize(64, 64))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/groot/move.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_ALIGN.setIcon(icon6)
        self.BTN_ALIGN.setIconSize(QtCore.QSize(32, 32))
        self.BTN_ALIGN.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_ALIGN.setObjectName("BTN_ALIGN")
        self.horizontalLayout_2.addWidget(self.BTN_ALIGN)
        self.BTN_OPTIONS = QtWidgets.QToolButton(self.groupBox_2)
        self.BTN_OPTIONS.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_OPTIONS.setMaximumSize(QtCore.QSize(64, 64))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/groot/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_OPTIONS.setIcon(icon7)
        self.BTN_OPTIONS.setIconSize(QtCore.QSize(32, 32))
        self.BTN_OPTIONS.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_OPTIONS.setObjectName("BTN_OPTIONS")
        self.horizontalLayout_2.addWidget(self.BTN_OPTIONS)
        self.horizontalLayout_23.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.FRA_MAIN = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FRA_MAIN.sizePolicy().hasHeightForWidth())
        self.FRA_MAIN.setSizePolicy(sizePolicy)
        self.FRA_MAIN.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FRA_MAIN.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FRA_MAIN.setObjectName("FRA_MAIN")
        self.verticalLayout.addWidget(self.FRA_MAIN)
        self.LBL_NO_DOMAINS = QtWidgets.QLabel(Dialog)
        self.LBL_NO_DOMAINS.setObjectName("LBL_NO_DOMAINS")
        self.verticalLayout.addWidget(self.LBL_NO_DOMAINS)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.GRP_WORKFLOW.setTitle(_translate("Dialog", "Workflow"))
        self.BTN_WORKFLOW.setText(_translate("Dialog", "Workflow"))
        self.BTN_CREATE.setText(_translate("Dialog", "Create"))
        self.BTN_REMOVE.setText(_translate("Dialog", "Remove"))
        self.BTN_VIEW.setText(_translate("Dialog", "View"))
        self.groupBox_2.setTitle(_translate("Dialog", "Viewer"))
        self.BTN_CHANGE_SELECTION.setToolTip(_translate("Dialog", "<html><head/><body><p>Switch to edge edit mode.</p></body></html>"))
        self.BTN_CHANGE_SELECTION.setStatusTip(_translate("Dialog", "Remove edge"))
        self.BTN_CHANGE_SELECTION.setText(_translate("Dialog", "Select"))
        self.BTN_REFRESH.setToolTip(_translate("Dialog", "<html><head/><body><p>Switch to edge edit mode.</p></body></html>"))
        self.BTN_REFRESH.setStatusTip(_translate("Dialog", "Remove edge"))
        self.BTN_REFRESH.setText(_translate("Dialog", "Refresh"))
        self.BTN_ALIGN.setText(_translate("Dialog", "Move"))
        self.BTN_OPTIONS.setText(_translate("Dialog", "Options"))
        self.LBL_NO_DOMAINS.setText(_translate("Dialog", "<html><head/><body><p>You have no <a href=\"action:view_domains\">domains</a> defined, all genes will be shown as one domain.</p></body></html>"))
        self.LBL_NO_DOMAINS.setProperty("style", _translate("Dialog", "warning"))


