---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-elasticsearch"
  galaxy_url: "https://galaxy.ansible.com/debops/elasticsearch"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Nick Janetakis'
      email: 'nick.janetakis@gmail.com'
      twitter: 'nickjanetakis'
      github: 'nickjj'

    - name:  'Maciej Delmanowski'
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    [Elasticsearch](https://en.wikipedia.org/wiki/Elasticsearch) is a distributed
    search engine and storage system, also a part of the Elasticsearch, Logstash,
    Kibana (ELK) stack. The software is developed by [Elastic](https://elastic.co/).

    The `debops.elasticsearch` Ansible role can be used to deploy and manage
    Elasticsearch instances on one or more (3+) hosts. The role can be used as
    a dependency by other Ansible roles to allow control over their configuration
    options in the Elasticsearch configuration file.
