dist: trusty
sudo: false
language: python

python:
- nightly
- &latest_py3 3.6

jobs:
  fast_finish: true
  include:
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    install: skip
    script: skip
    deploy:
      provider: pypi
      on:
        tags: true
        all_branches: true
      user: jaraco
      password:
        secure: aIj+bSsKqvSNFSoq5rEbQa8idK3zoASyjafr4WHCpp/ALwfAPe0NqSm0O0EG/XpvhRuphwCyI3jgbklYv/rl3GOXj69MVcwFe4nNwgFRIADXTVXnddN8F2ur4wrlprHZ8Gp3lgZCGEHe9x6N2tqk7tQvFxwzQ6IvMY4HOlHdoEPxk48M5Iyswc4plYkQV2vHbPb7k2+MdRR/t/nQ7giTncHO+hZ3GFAzgteLJAs38RitQu580w47RL1Km4c2Lqt3+5IRhHLrbyADgNRWurPxfUmEu2+1/NoZAEpAKv5XnVR8gv68y4bpINbcxEOxqjQlveDdFgyr/lxq3YSh3PhYvXE/YdnuOYbmy1ILVmJ9YWYL9CPS63rL8sbR7Fi9SDY3hsrNF/vMINXm5D6TjT2MYg0NDKm+NrlauMO1tAc67KK/KRM9KWnipaS1UYWAn0PxxXTHSzuOOE8wXJ6Mkn+1LmonTkU5AriXt993GQPgEhiwshNyFB1OJehRCPN+tKzMhtT4SMR7bBwghQ8F2QaUPE05FDgrNqI62UL6xxjC78AQTq8IdVtrp7LDwrwOwL2B5/GTd/xhltBGvr/AnmOVjk1XHou2oTBcs+KSAcf7c1okj8YZ8qIbJnVScbuKhUgfVby7i2w1f69zxaNf3SGkVqdccoSNaLK2Z8FcpA2iM0k=
      distributions: dists
      skip_cleanup: true
      skip_upload_docs: true

cache: pip

install:
- pip install tox tox-venv

script: tox
