#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['Click>=5,<7']

entry_points = \
{'console_scripts': ['random = random_cli:random_cli']}

setup(name='random_cli',
      version='0.1.2',
      description='a cli app that simply generates a random 64 character alphanumeric string.',
      author='Sunny Yiu',
      author_email='sun@yiu.co',
      url='https://github.com/sunnz/random-cli.py',
      py_modules=['random_cli'],
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='~=3.6',
     )
