dist: trusty
sudo: required
language: python
python:
    #  - 2.7 #TODO - Right now the tests require 'builtin' import, so we'll need to import this from the future module
  - 3.5
before_script:
- make ci-setup
script:
- make test

# Only email on failure
notifications:
  email:
    on_success: never
    on_failure: always
