language: python
python: 2.7
sudo: false
install:
  - pip install setuptools-git tox-travis
script:
  - tox
notifications:
  irc:
    - "irc.freenode.org#bsdploy"
  on_success: change
  on_failure: change
