sudo: false
osx_image: xcode7.1

language: objective-c

before_install:
- brew install python3

script:
- python setup.py build
- python setup.py test
- python3 setup.py build
- python3 setup.py test

notifications:
  email:
    on_success: never
    on_failure: change
