
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-03-14T10:45:56-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa3d651c6bd9b127533cd21ef8b933b925e2467d",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
