# -*- coding: utf-8 -*-
from __future__ import unicode_literals
# Generated by Django 1.11 on 2017-05-03 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0003_delete_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bairro',
            old_name='cidade',
            new_name='municipio',
        ),
    ]
