---
version: 1
formatters:
        simpleFormatter:
                format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
                datefmt: ''
        shortFormatter:
                format: '%(asctime)s - %(levelname)s - %(message)s'
                datefmt: ''

handlers:
        consoleHandler:
                class: logging.StreamHandler
                level: WARNING
                formatter: shortFormatter
                #stream: sys.stdout
loggers:
        pkgdb_client:
                level: INFO
                handlers: [consoleHandler]
                qualname: gofedlib.distribution.clients.pkgdb.client
                propagate: 0
        distribution_capturer:
                level: INFO
                handlers: [consoleHandler]
                qualname: gofedlib.distribution.eco.capturer
                propagate: 0
        distribution_snapshot_capturer:
                level: INFO
                handlers: [consoleHandler]
                qualname: gofed_infra.system.models.ecosnapshots.distributionsnapshotchecker
                propagate: 0
        distribution_packages_fetcher:
                level: INFO
                handlers: [consoleHandler]
                # if not set, the info get printed by more loggers :D
                propagate: 0
        distribution_latest_builds_dataset_builder:
                level: INFO
                handlers: [consoleHandler]
                propagate: 0
        simple_file_storage:
                level: WARNING
                handlers: [consoleHandler]
                propagate: 0
        scan_distribution_build_act:
                level: WARNING
                handlers: [consoleHandler]
                propagate: 0
        github_source_code_provider:
                level: INFO
                handlers: [consoleHandler]
                propagate: 0
root:
        level: WARNING
        handlers: [consoleHandler]

