---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/tinc"
  github_url: "https://github.com/debops/ansible-tinc"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:

    - name:  'Maciej Delmanowski'
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

    - name:  'Robin Schneider'
      email: 'ypid@riseup.net'
      github: 'ypid'

  synopsis: |
    [tinc](https://tinc-vpn.org/) is a Virtual Private Network daemon, it can be
    used to create encrypted and tunneled connections to other hosts, forming
    a separate network, either a centralized one or a mesh.

    `debops.tinc` Ansible role allows you to install and configure a mesh VPN
    using `tinc`, including automatic public key exchange between all hosts in
    the Ansible inventory, connection to external hosts and secure configuration.
