---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/authorized_keys"
  github_url: "https://github.com/debops/ansible-authorized_keys"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    The ``debops.authorized_keys`` role can be used to manage SSH keys centrally in
    the ``/etc/ssh/authorized_keys/`` directory. The role only manages the keys
    themselves, you should configure the ``sshd`` service to use them separately,
    for example by using the ``debops.sshd`` Ansible role.
