language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

env:
    - DJANGO=1.11.9

install:
    - pip install -q Django==$DJANGO
    - pip install -q -r requirements.txt
    - pip install -q -r requirements-testing.txt

before_script:
    - "pycodestyle --exclude=migrations --ignore=E501 helpdesk"

script:
    - coverage run --source='.' quicktest.py helpdesk

after_success:
    - codecov
