language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python setup.py build
  - python -m unittest
  - sphinx-apidoc --force --output-dir docs ebuildtester
  - sphinx-build -M doctest docs docs/_build
  - sphinx-build -M linkcheck docs docs/_build
  - sphinx-build -M coverage docs docs/_build
