
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d79ea442a2ba9de6a7b58c504f0d57cde1680b01",
 "version": "0.1.post20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
