# Config file for automatic testing at travis-ci.org

language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

# Command to install dependencies.
install:
    - pip install -r requirements-dev.txt
    - pip install --editable .
    - pip install tox-travis
    - pip install coveralls

# Command to run tests.
script:
    - flake8
    - pylint curver.kernel
    - tox -- --hypothesis-profile=ci

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls; fi

