---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/apt_listchanges"
  github_url: "https://github.com/debops/ansible-apt_listchanges"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    The `apt-listchanges` package is used to notify system administrator about
    package changes from Changelog and NEWS files. The role will configure this
    script to send that information via email messages to specified addresses.
