[package]
name = "poetry"
version = "0.2.0"
description = "Python dependency management and packaging made easy."

python-versions = ["^3.6"]

license = "MIT"

authors = [
    "Sébastien Eustace <sebastien@eustace.io>"
]

readme = "README.md"

homepage = "https://poetry.eustace.io/"
repository = "https://github.com/sdispater/poet"
documentation = "https://poetry.eustace.io/docs"

keywords = ["packaging", "dependency", "poetry"]

include = ['poetry/**/*', 'LICENSE']


[dependencies]
cleo = "^0.6"
requests = "^2.18"
toml = "^0.9"
cachy = "^0.1.0"
pip-tools = "^1.11"

[dev-dependencies]
pytest = "~3.4"


[scripts]
poetry = 'poetry:console.run'
