sudo: false
language: python


python:
  - 3.5
  - 3.6
  - 3.7-dev
  # - 'nightly'


os:
  - linux


install:
  - pip install -r requirements/ci.txt
  - pip install codecov

script:
  - make cov

after_success:
  - codecov

_helpers:
- &_skip_steps
  python: 3.6
  before_install: skip
  install: skip
  before_script: skip
  script: skip
  after_script: skip
  after_success: skip

jobs:
  include:
    - stage: doc
      <<: *_skip_steps
      install:
        - pip install -r requirements/doc.txt
      script: 
        - make doc

    - stage: deploy
      <<: *_skip_steps
      env:
        - FLIT_USERNAME=andrew.svetlov
        - secure: "UlJhfAPb0IWwFs/BZoiFHKxgoB2S1vkUNyjw8MXldUNPalR5eGh7ZXR+DiZpLGEl92vt4V7cpLqL9oY8GQeN6xczwipd/sc93ReG1qvGje/G3g7E5O3hIBio6ZXuO9Bsg9Xk6pQgIsnF6s9nZlu6rX/+Ru2U9n5CfeiznoTtfOUDc4I7JWdPbv7ks/RCYK/HQMrpDh55xGYH/6cSbKRVImCkehmg7bFprApn0RfZu3uuOYs89yjYfjNQxPoWlVF0yjAHJa3opdHzR1SlifTZotgSZwN5VWVV1XPqsrfdhTVYuziXsLmekL6jPbAJ4S85omG84Kns3bf0osWWTJ/E4CGrIQTAsz78yPaM/yFg/rwK3Zy4568y9FN+hIjVe/SyYTtSBWFgbZIYeIry2QFnN910TJ33t4qFyaw763rfHNGEZd1sh5w24Jh1JmhGZUk1QyGOk3GZWhZkaMF8qqL6xWnkPy+FKauXKeYaq73nhU4zCswDw9fVpr22Dz27MYh0hEyVLy+30Iaxab8x0wUQdlouTjPacgRUHkH1itsN6xuMOnisvdY8foVee/yDq9qHI8dkUhCtbNgT3rK03LYoIDFOiay4vxGEkhtTAdrpoiDVf7Py7jIezdt8tlqlAFsZOSi6z/1YRlNBhgloTh9Mh/eSKQbCWamNudmjolmuQRA="  # FLIT_PASSWORD
      install:
        - pip install -r requirements/deploy.txt
      script:
        - flit build
        - flit publish


stages:
  - name: doc
  - name: test
  - name: deploy
    # This will prevent deploy unless it's a tagged commit:
    if: tag IS present
