---

ansigenome_info:
  galaxy_url: 'https://galaxy.ansible.com/debops/debops_api'
  github_url: 'https://github.com/debops/ansible-debops_api'
  git_branch: 'master'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Robin Schneider'
      url: 'http://ypid.de/'
      email: 'ypid@riseup.net'
      twitter: 'ypid'
      github: 'ypid'

  synopsis: |
    ``debops.debops_api`` can be used to setup the [DebOps API][].

    [DebOps API]: https://github.com/debops/debops-api
