
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-21T17:58:53-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "fef04033eb7ae0e607c4c0600751cb428a999b7d",
 "version": "0.6.1rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
