---
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - make init
  - pip install coveralls sqlalchemy_utils

script:
  - make lint
  - make coverage

after_success:
  coveralls
