# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_big_text_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(977, 655)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.GRP_WORKFLOW = QtWidgets.QGroupBox(self.frame)
        self.GRP_WORKFLOW.setObjectName("GRP_WORKFLOW")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.GRP_WORKFLOW)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BTN_WORKFLOW = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_WORKFLOW.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_WORKFLOW.setMaximumSize(QtCore.QSize(64, 64))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/intermake/dropdown.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_WORKFLOW.setIcon(icon)
        self.BTN_WORKFLOW.setIconSize(QtCore.QSize(32, 32))
        self.BTN_WORKFLOW.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_WORKFLOW.setObjectName("BTN_WORKFLOW")
        self.horizontalLayout_2.addWidget(self.BTN_WORKFLOW)
        self.line_2 = QtWidgets.QFrame(self.GRP_WORKFLOW)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.BTN_CREATE = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_CREATE.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_CREATE.setMaximumSize(QtCore.QSize(64, 64))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/groot/create.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_CREATE.setIcon(icon1)
        self.BTN_CREATE.setIconSize(QtCore.QSize(32, 32))
        self.BTN_CREATE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_CREATE.setObjectName("BTN_CREATE")
        self.horizontalLayout_2.addWidget(self.BTN_CREATE)
        self.BTN_REMOVE = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_REMOVE.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_REMOVE.setMaximumSize(QtCore.QSize(64, 64))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/groot/remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_REMOVE.setIcon(icon2)
        self.BTN_REMOVE.setIconSize(QtCore.QSize(32, 32))
        self.BTN_REMOVE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_REMOVE.setObjectName("BTN_REMOVE")
        self.horizontalLayout_2.addWidget(self.BTN_REMOVE)
        self.BTN_VIEW = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_VIEW.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_VIEW.setMaximumSize(QtCore.QSize(64, 64))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/groot/view.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_VIEW.setIcon(icon3)
        self.BTN_VIEW.setIconSize(QtCore.QSize(32, 32))
        self.BTN_VIEW.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_VIEW.setObjectName("BTN_VIEW")
        self.horizontalLayout_2.addWidget(self.BTN_VIEW)
        self.horizontalLayout.addWidget(self.GRP_WORKFLOW)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BTN_SELECTION = QtWidgets.QToolButton(self.groupBox)
        self.BTN_SELECTION.setMinimumSize(QtCore.QSize(192, 64))
        self.BTN_SELECTION.setMaximumSize(QtCore.QSize(192, 64))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/groot/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SELECTION.setIcon(icon4)
        self.BTN_SELECTION.setIconSize(QtCore.QSize(32, 32))
        self.BTN_SELECTION.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.BTN_SELECTION.setObjectName("BTN_SELECTION")
        self.horizontalLayout_3.addWidget(self.BTN_SELECTION)
        self.gridGroupBox = QtWidgets.QGroupBox(self.groupBox)
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.CHK_MISCELLANEOUS = QtWidgets.QCheckBox(self.gridGroupBox)
        self.CHK_MISCELLANEOUS.setObjectName("CHK_MISCELLANEOUS")
        self.gridLayout.addWidget(self.CHK_MISCELLANEOUS, 0, 2, 1, 1)
        self.CHK_GRAPHS = QtWidgets.QCheckBox(self.gridGroupBox)
        self.CHK_GRAPHS.setObjectName("CHK_GRAPHS")
        self.gridLayout.addWidget(self.CHK_GRAPHS, 1, 1, 1, 1)
        self.CHK_FASTA = QtWidgets.QCheckBox(self.gridGroupBox)
        self.CHK_FASTA.setObjectName("CHK_FASTA")
        self.gridLayout.addWidget(self.CHK_FASTA, 0, 0, 1, 1)
        self.CHK_DATA = QtWidgets.QCheckBox(self.gridGroupBox)
        self.CHK_DATA.setObjectName("CHK_DATA")
        self.gridLayout.addWidget(self.CHK_DATA, 0, 1, 1, 1)
        self.CHK_ALIGNMENTS = QtWidgets.QCheckBox(self.gridGroupBox)
        self.CHK_ALIGNMENTS.setObjectName("CHK_ALIGNMENTS")
        self.gridLayout.addWidget(self.CHK_ALIGNMENTS, 1, 0, 1, 1)
        self.CHK_COLOURS = QtWidgets.QCheckBox(self.gridGroupBox)
        self.CHK_COLOURS.setObjectName("CHK_COLOURS")
        self.gridLayout.addWidget(self.CHK_COLOURS, 1, 2, 1, 1)
        self.horizontalLayout_3.addWidget(self.gridGroupBox)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.BTN_REFRESH = QtWidgets.QToolButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_REFRESH.sizePolicy().hasHeightForWidth())
        self.BTN_REFRESH.setSizePolicy(sizePolicy)
        self.BTN_REFRESH.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_REFRESH.setMaximumSize(QtCore.QSize(64, 64))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/groot/refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_REFRESH.setIcon(icon5)
        self.BTN_REFRESH.setIconSize(QtCore.QSize(32, 32))
        self.BTN_REFRESH.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_REFRESH.setObjectName("BTN_REFRESH")
        self.horizontalLayout_3.addWidget(self.BTN_REFRESH)
        self.BTN_SAVE = QtWidgets.QToolButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_SAVE.sizePolicy().hasHeightForWidth())
        self.BTN_SAVE.setSizePolicy(sizePolicy)
        self.BTN_SAVE.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_SAVE.setMaximumSize(QtCore.QSize(64, 64))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/groot/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SAVE.setIcon(icon6)
        self.BTN_SAVE.setIconSize(QtCore.QSize(32, 32))
        self.BTN_SAVE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_SAVE.setObjectName("BTN_SAVE")
        self.horizontalLayout_3.addWidget(self.BTN_SAVE)
        self.horizontalLayout.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.TXT_MAIN = QtWidgets.QTextBrowser(Dialog)
        self.TXT_MAIN.setObjectName("TXT_MAIN")
        self.verticalLayout.addWidget(self.TXT_MAIN)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.GRP_WORKFLOW.setTitle(_translate("Dialog", "Workflow"))
        self.BTN_WORKFLOW.setText(_translate("Dialog", "Workflow"))
        self.BTN_CREATE.setText(_translate("Dialog", "Create"))
        self.BTN_REMOVE.setText(_translate("Dialog", "Remove"))
        self.BTN_VIEW.setText(_translate("Dialog", "View"))
        self.groupBox.setTitle(_translate("Dialog", "Viewer"))
        self.BTN_SELECTION.setText(_translate("Dialog", "Selection"))
        self.gridGroupBox.setTitle(_translate("Dialog", "Show"))
        self.CHK_MISCELLANEOUS.setText(_translate("Dialog", "Misc."))
        self.CHK_GRAPHS.setText(_translate("Dialog", "Graphs"))
        self.CHK_FASTA.setText(_translate("Dialog", "FASTA"))
        self.CHK_DATA.setText(_translate("Dialog", "Tables"))
        self.CHK_ALIGNMENTS.setText(_translate("Dialog", "Alignments"))
        self.CHK_COLOURS.setText(_translate("Dialog", "Colours"))
        self.BTN_REFRESH.setText(_translate("Dialog", "Refresh"))
        self.BTN_SAVE.setText(_translate("Dialog", "Save"))


