# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_main_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1682, 1089)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.MDI_AREA = QtWidgets.QMdiArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MDI_AREA.sizePolicy().hasHeightForWidth())
        self.MDI_AREA.setSizePolicy(sizePolicy)
        self.MDI_AREA.setTabsClosable(True)
        self.MDI_AREA.setTabsMovable(True)
        self.MDI_AREA.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.MDI_AREA.setObjectName("MDI_AREA")
        self.gridLayout.addWidget(self.MDI_AREA, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BTN_NEW = QtWidgets.QToolButton(self.groupBox)
        self.BTN_NEW.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_NEW.setMaximumSize(QtCore.QSize(64, 64))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/groot/new.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_NEW.setIcon(icon)
        self.BTN_NEW.setIconSize(QtCore.QSize(32, 32))
        self.BTN_NEW.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_NEW.setObjectName("BTN_NEW")
        self.horizontalLayout_2.addWidget(self.BTN_NEW)
        self.BTN_OPEN = QtWidgets.QToolButton(self.groupBox)
        self.BTN_OPEN.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_OPEN.setMaximumSize(QtCore.QSize(64, 64))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/groot/open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_OPEN.setIcon(icon1)
        self.BTN_OPEN.setIconSize(QtCore.QSize(32, 32))
        self.BTN_OPEN.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_OPEN.setObjectName("BTN_OPEN")
        self.horizontalLayout_2.addWidget(self.BTN_OPEN)
        self.BTN_SAVE = QtWidgets.QToolButton(self.groupBox)
        self.BTN_SAVE.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_SAVE.setMaximumSize(QtCore.QSize(64, 64))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/groot/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SAVE.setIcon(icon2)
        self.BTN_SAVE.setIconSize(QtCore.QSize(32, 32))
        self.BTN_SAVE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_SAVE.setObjectName("BTN_SAVE")
        self.horizontalLayout_2.addWidget(self.BTN_SAVE)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BTN_WORKFLOW = QtWidgets.QToolButton(self.groupBox_2)
        self.BTN_WORKFLOW.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_WORKFLOW.setMaximumSize(QtCore.QSize(64, 64))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/groot/workflow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_WORKFLOW.setIcon(icon3)
        self.BTN_WORKFLOW.setIconSize(QtCore.QSize(32, 32))
        self.BTN_WORKFLOW.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_WORKFLOW.setObjectName("BTN_WORKFLOW")
        self.horizontalLayout_3.addWidget(self.BTN_WORKFLOW)
        self.BTN_WIZARD = QtWidgets.QToolButton(self.groupBox_2)
        self.BTN_WIZARD.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_WIZARD.setMaximumSize(QtCore.QSize(64, 64))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/groot/wizard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_WIZARD.setIcon(icon4)
        self.BTN_WIZARD.setIconSize(QtCore.QSize(32, 32))
        self.BTN_WIZARD.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_WIZARD.setObjectName("BTN_WIZARD")
        self.horizontalLayout_3.addWidget(self.BTN_WIZARD)
        self.BTN_SETTINGS = QtWidgets.QToolButton(self.groupBox_2)
        self.BTN_SETTINGS.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_SETTINGS.setMaximumSize(QtCore.QSize(64, 64))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/groot/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SETTINGS.setIcon(icon5)
        self.BTN_SETTINGS.setIconSize(QtCore.QSize(32, 32))
        self.BTN_SETTINGS.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_SETTINGS.setObjectName("BTN_SETTINGS")
        self.horizontalLayout_3.addWidget(self.BTN_SETTINGS)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setMinimumSize(QtCore.QSize(16, 0))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.BTN_VIEW_TEXT = QtWidgets.QToolButton(self.groupBox_2)
        self.BTN_VIEW_TEXT.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_VIEW_TEXT.setMaximumSize(QtCore.QSize(64, 64))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/groot/text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_VIEW_TEXT.setIcon(icon6)
        self.BTN_VIEW_TEXT.setIconSize(QtCore.QSize(32, 32))
        self.BTN_VIEW_TEXT.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_VIEW_TEXT.setObjectName("BTN_VIEW_TEXT")
        self.horizontalLayout_3.addWidget(self.BTN_VIEW_TEXT)
        self.BTN_VIEW_LEGO = QtWidgets.QToolButton(self.groupBox_2)
        self.BTN_VIEW_LEGO.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_VIEW_LEGO.setMaximumSize(QtCore.QSize(64, 64))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/groot/lego.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_VIEW_LEGO.setIcon(icon7)
        self.BTN_VIEW_LEGO.setIconSize(QtCore.QSize(32, 32))
        self.BTN_VIEW_LEGO.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_VIEW_LEGO.setObjectName("BTN_VIEW_LEGO")
        self.horizontalLayout_3.addWidget(self.BTN_VIEW_LEGO)
        self.BTN_VIEW_ALIGNMENT = QtWidgets.QToolButton(self.groupBox_2)
        self.BTN_VIEW_ALIGNMENT.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_VIEW_ALIGNMENT.setMaximumSize(QtCore.QSize(64, 64))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/groot/align.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_VIEW_ALIGNMENT.setIcon(icon8)
        self.BTN_VIEW_ALIGNMENT.setIconSize(QtCore.QSize(32, 32))
        self.BTN_VIEW_ALIGNMENT.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_VIEW_ALIGNMENT.setObjectName("BTN_VIEW_ALIGNMENT")
        self.horizontalLayout_3.addWidget(self.BTN_VIEW_ALIGNMENT)
        self.BTN_VIEW_TREES = QtWidgets.QToolButton(self.groupBox_2)
        self.BTN_VIEW_TREES.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_VIEW_TREES.setMaximumSize(QtCore.QSize(64, 64))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/groot/tree.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_VIEW_TREES.setIcon(icon9)
        self.BTN_VIEW_TREES.setIconSize(QtCore.QSize(32, 32))
        self.BTN_VIEW_TREES.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_VIEW_TREES.setObjectName("BTN_VIEW_TREES")
        self.horizontalLayout_3.addWidget(self.BTN_VIEW_TREES)
        self.BTN_DATABASE = QtWidgets.QToolButton(self.groupBox_2)
        self.BTN_DATABASE.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_DATABASE.setMaximumSize(QtCore.QSize(64, 64))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/groot/database.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_DATABASE.setIcon(icon10)
        self.BTN_DATABASE.setIconSize(QtCore.QSize(32, 32))
        self.BTN_DATABASE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_DATABASE.setObjectName("BTN_DATABASE")
        self.horizontalLayout_3.addWidget(self.BTN_DATABASE)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.BTN_BLAST = QtWidgets.QToolButton(self.groupBox_3)
        self.BTN_BLAST.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_BLAST.setMaximumSize(QtCore.QSize(64, 64))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/groot/edge.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_BLAST.setIcon(icon11)
        self.BTN_BLAST.setIconSize(QtCore.QSize(32, 32))
        self.BTN_BLAST.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_BLAST.setObjectName("BTN_BLAST")
        self.horizontalLayout_4.addWidget(self.BTN_BLAST)
        self.BTN_FASTA = QtWidgets.QToolButton(self.groupBox_3)
        self.BTN_FASTA.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_FASTA.setMaximumSize(QtCore.QSize(64, 64))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/groot/sequence.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_FASTA.setIcon(icon12)
        self.BTN_FASTA.setIconSize(QtCore.QSize(32, 32))
        self.BTN_FASTA.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_FASTA.setObjectName("BTN_FASTA")
        self.horizontalLayout_4.addWidget(self.BTN_FASTA)
        self.BTN_COMPONENTS = QtWidgets.QToolButton(self.groupBox_3)
        self.BTN_COMPONENTS.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_COMPONENTS.setMaximumSize(QtCore.QSize(64, 64))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/groot/compartmentalise.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_COMPONENTS.setIcon(icon13)
        self.BTN_COMPONENTS.setIconSize(QtCore.QSize(32, 32))
        self.BTN_COMPONENTS.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_COMPONENTS.setObjectName("BTN_COMPONENTS")
        self.horizontalLayout_4.addWidget(self.BTN_COMPONENTS)
        self.BTN_DOMAINS = QtWidgets.QToolButton(self.groupBox_3)
        self.BTN_DOMAINS.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_DOMAINS.setMaximumSize(QtCore.QSize(64, 64))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/groot/domain.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_DOMAINS.setIcon(icon14)
        self.BTN_DOMAINS.setIconSize(QtCore.QSize(32, 32))
        self.BTN_DOMAINS.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_DOMAINS.setObjectName("BTN_DOMAINS")
        self.horizontalLayout_4.addWidget(self.BTN_DOMAINS)
        self.BTN_ALIGNMENT = QtWidgets.QToolButton(self.groupBox_3)
        self.BTN_ALIGNMENT.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_ALIGNMENT.setMaximumSize(QtCore.QSize(64, 64))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/groot/align_component.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_ALIGNMENT.setIcon(icon15)
        self.BTN_ALIGNMENT.setIconSize(QtCore.QSize(32, 32))
        self.BTN_ALIGNMENT.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_ALIGNMENT.setObjectName("BTN_ALIGNMENT")
        self.horizontalLayout_4.addWidget(self.BTN_ALIGNMENT)
        self.BTN_TREES = QtWidgets.QToolButton(self.groupBox_3)
        self.BTN_TREES.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_TREES.setMaximumSize(QtCore.QSize(64, 64))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/groot/black_tree.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_TREES.setIcon(icon16)
        self.BTN_TREES.setIconSize(QtCore.QSize(32, 32))
        self.BTN_TREES.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_TREES.setObjectName("BTN_TREES")
        self.horizontalLayout_4.addWidget(self.BTN_TREES)
        self.BTN_FUSIONS = QtWidgets.QToolButton(self.groupBox_3)
        self.BTN_FUSIONS.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_FUSIONS.setMaximumSize(QtCore.QSize(64, 64))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/groot/fuse.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_FUSIONS.setIcon(icon17)
        self.BTN_FUSIONS.setIconSize(QtCore.QSize(32, 32))
        self.BTN_FUSIONS.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_FUSIONS.setObjectName("BTN_FUSIONS")
        self.horizontalLayout_4.addWidget(self.BTN_FUSIONS)
        self.BTN_SPLITS = QtWidgets.QToolButton(self.groupBox_3)
        self.BTN_SPLITS.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_SPLITS.setMaximumSize(QtCore.QSize(64, 64))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/groot/split.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SPLITS.setIcon(icon18)
        self.BTN_SPLITS.setIconSize(QtCore.QSize(32, 32))
        self.BTN_SPLITS.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_SPLITS.setObjectName("BTN_SPLITS")
        self.horizontalLayout_4.addWidget(self.BTN_SPLITS)
        self.BTN_CONSENSUS = QtWidgets.QToolButton(self.groupBox_3)
        self.BTN_CONSENSUS.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_CONSENSUS.setMaximumSize(QtCore.QSize(64, 64))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/groot/consensus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_CONSENSUS.setIcon(icon19)
        self.BTN_CONSENSUS.setIconSize(QtCore.QSize(32, 32))
        self.BTN_CONSENSUS.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_CONSENSUS.setObjectName("BTN_CONSENSUS")
        self.horizontalLayout_4.addWidget(self.BTN_CONSENSUS)
        self.BTN_SUBSETS = QtWidgets.QToolButton(self.groupBox_3)
        self.BTN_SUBSETS.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_SUBSETS.setMaximumSize(QtCore.QSize(64, 64))
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/groot/subset.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SUBSETS.setIcon(icon20)
        self.BTN_SUBSETS.setIconSize(QtCore.QSize(32, 32))
        self.BTN_SUBSETS.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_SUBSETS.setObjectName("BTN_SUBSETS")
        self.horizontalLayout_4.addWidget(self.BTN_SUBSETS)
        self.BTN_SUBGRAPHS = QtWidgets.QToolButton(self.groupBox_3)
        self.BTN_SUBGRAPHS.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_SUBGRAPHS.setMaximumSize(QtCore.QSize(64, 64))
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/groot/minigraph.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SUBGRAPHS.setIcon(icon21)
        self.BTN_SUBGRAPHS.setIconSize(QtCore.QSize(32, 32))
        self.BTN_SUBGRAPHS.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_SUBGRAPHS.setObjectName("BTN_SUBGRAPHS")
        self.horizontalLayout_4.addWidget(self.BTN_SUBGRAPHS)
        self.BTN_NRFG = QtWidgets.QToolButton(self.groupBox_3)
        self.BTN_NRFG.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_NRFG.setMaximumSize(QtCore.QSize(64, 64))
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/groot/stitch.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_NRFG.setIcon(icon22)
        self.BTN_NRFG.setIconSize(QtCore.QSize(32, 32))
        self.BTN_NRFG.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_NRFG.setObjectName("BTN_NRFG")
        self.horizontalLayout_4.addWidget(self.BTN_NRFG)
        self.BTN_CLEAN = QtWidgets.QToolButton(self.groupBox_3)
        self.BTN_CLEAN.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_CLEAN.setMaximumSize(QtCore.QSize(64, 64))
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/groot/clean.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_CLEAN.setIcon(icon23)
        self.BTN_CLEAN.setIconSize(QtCore.QSize(32, 32))
        self.BTN_CLEAN.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_CLEAN.setObjectName("BTN_CLEAN")
        self.horizontalLayout_4.addWidget(self.BTN_CLEAN)
        self.BTN_CHECK = QtWidgets.QToolButton(self.groupBox_3)
        self.BTN_CHECK.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_CHECK.setMaximumSize(QtCore.QSize(64, 64))
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/groot/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_CHECK.setIcon(icon24)
        self.BTN_CHECK.setIconSize(QtCore.QSize(32, 32))
        self.BTN_CHECK.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_CHECK.setObjectName("BTN_CHECK")
        self.horizontalLayout_4.addWidget(self.BTN_CHECK)
        self.horizontalLayout.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1682, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "File"))
        self.BTN_NEW.setText(_translate("MainWindow", "New"))
        self.BTN_OPEN.setText(_translate("MainWindow", "Open"))
        self.BTN_SAVE.setText(_translate("MainWindow", "Save"))
        self.groupBox_2.setTitle(_translate("MainWindow", "View"))
        self.BTN_WORKFLOW.setText(_translate("MainWindow", "Workflow"))
        self.BTN_WIZARD.setText(_translate("MainWindow", "Wizard"))
        self.BTN_SETTINGS.setText(_translate("MainWindow", "Settings"))
        self.BTN_VIEW_TEXT.setText(_translate("MainWindow", "Data"))
        self.BTN_VIEW_LEGO.setText(_translate("MainWindow", "Lego"))
        self.BTN_VIEW_ALIGNMENT.setText(_translate("MainWindow", "Alignment"))
        self.BTN_VIEW_TREES.setText(_translate("MainWindow", "Trees"))
        self.BTN_DATABASE.setText(_translate("MainWindow", "Database"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Workflow"))
        self.BTN_BLAST.setText(_translate("MainWindow", "BLAST"))
        self.BTN_FASTA.setText(_translate("MainWindow", "FASTA"))
        self.BTN_COMPONENTS.setText(_translate("MainWindow", "Components"))
        self.BTN_DOMAINS.setText(_translate("MainWindow", "Domains"))
        self.BTN_ALIGNMENT.setText(_translate("MainWindow", "Alignment"))
        self.BTN_TREES.setText(_translate("MainWindow", "Trees"))
        self.BTN_FUSIONS.setText(_translate("MainWindow", "Fusions"))
        self.BTN_SPLITS.setText(_translate("MainWindow", "Splits"))
        self.BTN_CONSENSUS.setText(_translate("MainWindow", "Consensus"))
        self.BTN_SUBSETS.setText(_translate("MainWindow", "Subsets"))
        self.BTN_SUBGRAPHS.setText(_translate("MainWindow", "Subgraphs"))
        self.BTN_NRFG.setText(_translate("MainWindow", "NRFG"))
        self.BTN_CLEAN.setText(_translate("MainWindow", "Clean"))
        self.BTN_CHECK.setText(_translate("MainWindow", "Check"))


