# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_view_splits_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1084, 762)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_23.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_23.setSpacing(8)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.GRP_WORKFLOW = QtWidgets.QGroupBox(self.frame)
        self.GRP_WORKFLOW.setObjectName("GRP_WORKFLOW")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.GRP_WORKFLOW)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BTN_WORKFLOW = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_WORKFLOW.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_WORKFLOW.setMaximumSize(QtCore.QSize(64, 64))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/intermake/dropdown.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_WORKFLOW.setIcon(icon)
        self.BTN_WORKFLOW.setIconSize(QtCore.QSize(32, 32))
        self.BTN_WORKFLOW.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_WORKFLOW.setObjectName("BTN_WORKFLOW")
        self.horizontalLayout.addWidget(self.BTN_WORKFLOW)
        self.line_3 = QtWidgets.QFrame(self.GRP_WORKFLOW)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.BTN_CREATE = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_CREATE.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_CREATE.setMaximumSize(QtCore.QSize(64, 64))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/groot/create.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_CREATE.setIcon(icon1)
        self.BTN_CREATE.setIconSize(QtCore.QSize(32, 32))
        self.BTN_CREATE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_CREATE.setObjectName("BTN_CREATE")
        self.horizontalLayout.addWidget(self.BTN_CREATE)
        self.BTN_REMOVE = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_REMOVE.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_REMOVE.setMaximumSize(QtCore.QSize(64, 64))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/groot/remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_REMOVE.setIcon(icon2)
        self.BTN_REMOVE.setIconSize(QtCore.QSize(32, 32))
        self.BTN_REMOVE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_REMOVE.setObjectName("BTN_REMOVE")
        self.horizontalLayout.addWidget(self.BTN_REMOVE)
        self.BTN_VIEW = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_VIEW.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_VIEW.setMaximumSize(QtCore.QSize(64, 64))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/groot/view.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_VIEW.setIcon(icon3)
        self.BTN_VIEW.setIconSize(QtCore.QSize(32, 32))
        self.BTN_VIEW.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_VIEW.setObjectName("BTN_VIEW")
        self.horizontalLayout.addWidget(self.BTN_VIEW)
        self.horizontalLayout_23.addWidget(self.GRP_WORKFLOW)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BTN_CHANGE_SELECTION = QtWidgets.QToolButton(self.groupBox_2)
        self.BTN_CHANGE_SELECTION.setMinimumSize(QtCore.QSize(192, 64))
        self.BTN_CHANGE_SELECTION.setMaximumSize(QtCore.QSize(192, 64))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/groot/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_CHANGE_SELECTION.setIcon(icon4)
        self.BTN_CHANGE_SELECTION.setIconSize(QtCore.QSize(32, 32))
        self.BTN_CHANGE_SELECTION.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.BTN_CHANGE_SELECTION.setObjectName("BTN_CHANGE_SELECTION")
        self.horizontalLayout_2.addWidget(self.BTN_CHANGE_SELECTION)
        self.horizontalLayout_23.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.LST_SPLITS = QtWidgets.QTreeWidget(Dialog)
        self.LST_SPLITS.setObjectName("LST_SPLITS")
        self.LST_SPLITS.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.LST_SPLITS)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.GRP_WORKFLOW.setTitle(_translate("Dialog", "Workflow"))
        self.BTN_WORKFLOW.setText(_translate("Dialog", "Workflow"))
        self.BTN_CREATE.setText(_translate("Dialog", "Create"))
        self.BTN_REMOVE.setText(_translate("Dialog", "Remove"))
        self.BTN_VIEW.setText(_translate("Dialog", "View"))
        self.groupBox_2.setTitle(_translate("Dialog", "Viewer"))
        self.BTN_CHANGE_SELECTION.setToolTip(_translate("Dialog", "<html><head/><body><p>Switch to edge edit mode.</p></body></html>"))
        self.BTN_CHANGE_SELECTION.setStatusTip(_translate("Dialog", "Remove edge"))
        self.BTN_CHANGE_SELECTION.setText(_translate("Dialog", "Select"))
        self.label.setText(_translate("Dialog", "TextLabel"))
        self.label.setProperty("style", _translate("Dialog", "header"))


