
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-26T19:22:30+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "76c60ab84186ab893c7b3dc340919a8b89c68ccf",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
