---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/resources"
  github_url: "https://github.com/debops/ansible-resources"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    This role allows management of custom file paths, file contents and archives on
    remote hosts without the need to create a separate Ansible role. You can use
    inventory lists to define what files to copy, what directories should exist on
    a remote host, what online resources to download, etc.

