---
version: 2
workers:
- type: router
  realms:
  - name: realm1
    roles:
    - name: authorized_users
      permissions:
      - uri: ''
        match: prefix
        allow: {call: true, publish: true, register: true, subscribe: true}
        disclose: {caller: true, publisher: true}
    - name: anonymous
      permissions:
      - uri: ''
        match: prefix
        allow: {call: true, publish: true, register: true, subscribe: true}
  transports:
  - type: websocket
    endpoint:
      type: tcp
      port: 8080
    auth:
      anonymous:
        type: static
        role: anonymous
      wampcra:
        type: static
        users:
          testuser:
            secret: testpass
            role: authorized_users
      ticket:
        type: static
        principals:
          device1:
            ticket: abc123
            role: authorized_users
