
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-27T10:01:39-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e7b489f855eef9aba781fe3451ffd098d1beead7",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
