---

ansigenome_info:
  galaxy_url: "https://github.com/debops/ansible-saslauthd"
  github_url: "https://github.com/debops/ansible-saslauthd"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    [Cyrus SASL library](https://www.cyrusimap.org/docs/cyrus-sasl/2.1.25/) is
    part of the Cyrus IMAP project and can be used to authenticate access to
    different services that implement
    [Simple Authentication Security Layer](https://en.wikipedia.org/wiki/Simple_Authentication_and_Security_Layer)
    support.

    This role allows configuration of multiple `saslauthd` instances which
    can be used by different services. By default role can configure support for
    SMTP AUTH for Postfix, other services might be supported in the future.
