---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/rabbitmq_server"
  github_url: "https://github.com/debops/ansible-rabbitmq_server"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    [RabbitMQ](https://www.rabbitmq.com/) is an Open Source message broker which
    supports AMQP, STOMP and MQTT protocols.
    
    This Ansible role can be used to install and manage RabbitMQ service on
    Debian/Ubuntu hosts.
