branches:
  except:
    - gh-pages

install:
  - set PATH=C:\Python36;%PATH%
  - cmake --version
  - pip install conan
  - conan user
  - conan --version

build_script:
  - mkdir build
  - cd build
  - cmake .. -DCLI_SINGLE_FILE_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_GENERATOR="Visual Studio 14 2015"
  - cmake --build .
  - cd ..
  - conan create . CLIUtils/CLI11

test_script:
  - ctest --output-on-failure -C Debug

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/0185e91c5d989a476d7b
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
