# This deliberately is not "python" as a work-around to support
# multi-os builds with custom Python versions in Travis CI.
language: cpp

os: 
  - osx
  - linux 

env:
  matrix:
    - PYTHON_EXE="`pyenv install -s 2.7.13 && pyenv local 2.7.13`"
    - PYTHON_EXE="`pyenv install -s 3.5.3 && pyenv local 3.5.3`"
    - PYTHON_EXE="`pyenv install -s 3.6.1 && pyenv local 3.6.1`"

install:
  - pyenv install --list
  - ./configure

before_script:
  - bin/pip install aboutcode-toolkit
  - bin/about-code check --show-all .

script:
  - "bin/py.test -vvs"

notifications:
  irc:
    channels:
      - "chat.freenode.net#aboutcode"
  on_success: change
  on_failure: always
  use_notice: true
  skip_join: true
  template:
    - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} : %{build_url}"
