- project:
    name: openstack/osprofiler
    check:
      jobs:
        - openstack-tox-functional
        - openstack-tox-functional-py35
    gate:
      jobs:
        - openstack-tox-functional
        - openstack-tox-functional-py35
