---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/etherpad"
  github_url: "https://github.com/debops/ansible-etherpad"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

    - name:  'Robin Schneider'
      url: 'http://ypid.de/'
      email: 'ypid@riseup.net'
      twitter: 'ypid'
      github: 'ypid'

  synopsis: |
    [Etherpad](https://en.wikipedia.org/wiki/Etherpad) is a collaborative text
    editor usable through a web browser. Documents can be edited by multiple people
    in real time, shared and exported in different formats.

    This role can be used to deploy and configure [Etherpad Lite](https://github.com/ether/etherpad-lite),
    a NodeJS version of Etherpad, on a Debian/Ubuntu host. The application can use
    a MariaDB or SQLite database as a storage backend, and will be configured
    behind a Nginx proxy as a frontend.
