# Config file for automatic testing at travis-ci.org

# Only test maint, master and pull requests; skip tags.
# Other branches can allow themselves.
branches:
  only:
    - maint
    - master

# Prefer docker containers
sudo: required

language: python

python:
  - "3.6"

cache: pip

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=pypy

matrix:
  allow_failures:
    - env: TOXENV=pypy

install:
  - travis_retry pip install tox

script:
  - tox
