- hosts: all
  tasks:
    # packstack-integration-tempest role is inherited from
    # openstack/packstack project
    - name: Install packstack allinone
      include_role:
        name: packstack-integration-tempest
    # setup-tempest-user, setup-stack-user and setup-devstack-source-dirs
    # are inherited from openstack-dev/devstack
    - name: Setup Stack user
      include_role:
        name: setup-stack-user
    - name: Setup Tempest user
      include_role:
        name: setup-tempest-user
    - name: Setup Tempest user
      include_role:
        name: setup-devstack-source-dirs
    # setup-tempest-* and acl-devstack-files roles are inherited from
    # openstack/tempest project
    - name: Setup Tempest Run Directory
      include_role:
        name: setup-tempest-run-dir
    - name: Setup Tempest Data Directory
      include_role:
        name: setup-tempest-data-dir
    - name: ACL devstack files
      include_role:
        name: acl-devstack-files
    - name: Prepare keystonerc credentials generated by packstack
      include_role:
        name: create-keystonerc-files
    - name: Generate configuration file for python-tempestconf
      include_role:
        name: generate-tempestconf-file
      vars:
        source_credentials_commands: "source {{ ansible_user_dir }}/keystonerc_{{ user }}"
    # run-tempest role is inherited from openstack/tempest project
    - name: Run Tempest Tests
      include_role:
        name: run-tempest
      vars:
        tempest_concurrency: 2
