# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-11 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_geo_db', '0003_location_county'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([('state', 'name', 'county')]),
        ),
    ]
