settings/general:
    # You can delay astrality on startup if other tasks need to finish first,
    # for example if you are automatically rearranging displays, which might
    # interfere with conky. The delay is given in seconds.
    startup_delay: 0


module/wallpaper:
    # A module for changing your wallpaper based on the suns position in the sky.
    enabled: true

    timer:
        # The solar timer provides the following periods:
        # sunrise, morning, afternoon, sunset, and night.
        type: solar

        # Since this is dependent on your exact location, you have to specify your
        # GPS coordinates. They are can be easily obtained from:
        # https://www.latlong.net/
        latitude: 63.446827
        longitude: 10.421906
        elevation: 0

        # You can force a timer to always return the same period for debugging reasons,
        # e.g. if you want to check if all your periodic color schemes fit your
        # periodic wallpapers.
        # force_period: morning

    on_startup:
        import_context:
            - from_file: wallpaper_themes/default/colors.yaml
              from_section: '{period}'
              to_section: colors
        compile:
            - conky.time
            - conky.performance

    on_period_change:
        run:
            - feh --bg-fill wallpaper_themes/default/{period}.*
        import_context:
            - from_file: wallpaper_themes/default/colors.yaml
              from_section: '{period}'
              to_section: colors
        compile:
            - conky.time
            - conky.performance

    on_exit:
        run:
            - feh --bg-fill wallpaper_themes/default/solid_black_background.jpeg

    # `import_section_on_period_change` can specify a string list with the format:
    # "section file_path {period}". It does the following after each "timer" period
    # change:
    #     - Find the yaml formatted file located at "file_path".
    #     - Retrieve the values defined in the section named the same as the
    #       current period, e.g. night.
    #     - Load the values into the section "section" of this configuration.
    #     - Recompile all templates with new values for ${ast:section:*}
    #
    # Here we change the colors of other templates based on the current wallpaper


module/conky:
    enabled: true

    templates:
        time:
            source: templates/conky_time.conf
        performance:
            source: templates/conky_performance.conf

    on_startup:
        run:
            - conky -c {time}
            - conky -c {performance}

    on_exit:
        run:
            - pkill -f conky


context/general:
    # It is possible to define further arbitrarily named sections.
    # For instance, with this option set, you can use ${ast:general:display} in all
    # your templates.
    display: eDP1

    # You can also use command substitution in order to insert the standard
    # output of a shell command into a configuration option.
    HDMI: $(xrandr | grep "HDMI2 connected")


context/fonts:
    # You can use integer indexed variables in order to have fallback values. If
    # ${ast:fonts:4} is used in a template, but it is not defined, it will be
    # replaced with ${ast:fonts:3} instead.
    1: FuraCode Nerd Font
    2: FuraMono Nerd Font
    3: RobotoMono Nerd Font

# vim:filetype=yaml
