---
# General information
title: Lab Notebook
author: C. Darwin
email: cdarwin@geolsoc.org.uk

# Search path for notebook entries
input_dirs:
  - example/research/*/*

# Location where notebook HTML should be saved to
output_file: example/research/index.html

# File types to include
include_files: ['*.html', '*.py', '*.txt']

# Files to exclude
exclude: ['private']

# Research categories
categories:
  Finches:
    patterns: ['finch', 'natural-selection']
    description: "Finch research from the second voyage of HMS Beagle"
    image: "images/a1417007h.jpg"
  Barnacles:
    patterns: ['cirripede']
    image: "images/1854_Balanidae_F339.2_figlbp12.jpg"

# Short-hand method of specifying categories
#categories:
#  'Finches': ['finch', 'natural-selection']  
#  'Barnacles': ['cirripede']  

sort_categories_by_date: false

# Notebook theme
theme: default

#
# Image sources
# -------------
#
# 1. Tanagra Darwini, 1840-1843
#      State Library New South Wales
#      http://www2.sl.nsw.gov.au/archive/events/exhibitions/2007/heritage/images/9.html
#
## 2. A monograph on the sub-class Cirripedia 
#      Darwin Online
#      http://darwin-online.org.uk/content/frameset?itemID=F339.2&viewtype=side&pageseq=1
#

