---

ansigenome_info:
  galaxy_url: "https://github.com/debops/ansible-unbound"
  github_url: "https://github.com/debops/ansible-unbound"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    [Unbound](https://unbound.net/) is a local DNS resolver. It supports
    [DNSSEC](https://en.wikipedia.org/wiki/DNSSEC) validation and can be used
    to ensure that DNS queries protected by DNSSEC are signed by the correct
    DNS root zone key, verified locally.
