
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2018-02-15T13:30:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "90f3a595a0f39bddb78056c1f05954c5df3d331c",
 "version": "0.4.3.post.dev13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
