---

ansigenome_info:
  galaxy_url: 'https://galaxy.ansible.com/debops/auth/'
  github_url: 'https://github.com/debops/ansible-auth'
  git_branch: 'master'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    `debops.auth` manages basic user authentication and authorization on
    configured host, including setting up system groups with elevated
    privileges.
