language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install numpy scipy cython
  - pip install pandas
  - pip install sklearn
  - pip install mdtraj
  - pip install nose
  - pip install -e .

script:
  # Your test script goes here
  - nosetests -v
