---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/users"
  github_url: "https://github.com/debops/ansible-users"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    The `debops.users` Ansible role can be used to manage local user accounts and
    groups. The role allows for certain operations inside of the home directories,
    like configuration of the mail forwarding, SSH public keys or automatic
    deployment of user configuration files (dotfiles).
