[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "tardigrade"
author = "Moshe Zadka"
author-email = "zadka.moshe@gmail.com"
home-page = "https://github.com/moshez/tardigrade"
classifiers = ["License :: OSI Approved :: MIT License"]

