#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['tardigrade']

package_data = \
{'': ['*']}

setup(name='tardigrade',
      version='2018.1.0',
      description='A thing',
      author='Moshe Zadka',
      author_email='zadka.moshe@gmail.com',
      url='https://github.com/moshez/tardigrade',
      packages=packages,
      package_data=package_data,
     )
