---

ansigenome_info:
  galaxy_url: 'https://galaxy.ansible.com/debops/redis'
  github_url: 'https://github.com/debops/ansible-redis'
  git_branch: 'master'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Nick Janetakis'
      url: ''
      email: 'nick.janetakis@gmail.com'
      twitter: 'nickjanetakis'
      github: 'nickjj'

    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    The `debops.redis` role allows you to easily setup infrastructure capable of
    running and managing 1 or more Redis servers. It is completely self healing
    with Redis Sentinel and supports replication seamlessly.
