
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-18T23:03:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8d6546978d13c2e97c6b7f30dc3b1873f2958b6b",
 "version": "v0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
