version: '2'
services:
    influxdb:
        restart: always
        image: 'influxdb:1.3-alpine'
        ports:
            - '8086'
            - '8083'
        volumes:
            - '${FAUCET_PREFIX}/opt/influxdb/shared/data/db:/var/lib/influxdb'
        environment:
            INFLUXDB_DB: 'faucet'
            INFLUXDB_HTTP_AUTH_ENABLED: 'true'
            INFLUXDB_ADMIN_USER: 'faucet'
            INFLUXDB_ADMIN_PASSWORD: 'faucet'

    couchdb:
        restart: always
        image: 'couchdb:1.6'
        volumes:
            - '${FAUCET_PREFIX}/opt/couchdb:/usr/local/var/lib/couchdb'
        environment:
            COUCHDB_USER: 'couch'
            COUCHDB_PASSWORD: '123'

    prometheus:
        restart: always
        image: 'prom/prometheus:v2.0.0'
        user: 'root'
        ports:
            - '9090:9090'
        volumes:
            - '${FAUCET_PREFIX}/opt/prometheus/:/prometheus'
            - './etc/prometheus/prometheus-docker-compose.yml:/etc/prometheus/prometheus.yml'
            - './etc/prometheus/faucet.rules.yml:/etc/prometheus/faucet.rules.yml'
        links:
            - faucet
            - gauge

    grafana:
        restart: always
        image: 'grafana/grafana:4.5.2'
        ports:
            - '3000:3000'
        volumes:
            - '${FAUCET_PREFIX}/opt/grafana:/var/lib/grafana'
        links:
            - influxdb
            - prometheus

    gauge:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.gauge
        image: 'faucet/gauge:latest'
        environment:
            GAUGE_CONFIG: '/etc/ryu/faucet/gauge.yaml'
        volumes:
            - '${FAUCET_PREFIX}/var/log/ryu/faucet:/var/log/ryu/faucet'
            - '${FAUCET_PREFIX}/etc/ryu/faucet:/etc/ryu/faucet'
        ports:
            - '6654:6653'
            - '9303'
        links:
            - couchdb
            - influxdb

    faucet:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        image: 'faucet/faucet:latest'
        volumes:
            - '${FAUCET_PREFIX}/var/log/ryu/faucet:/var/log/ryu/faucet'
            - '${FAUCET_PREFIX}/etc/ryu/faucet:/etc/ryu/faucet'
        ports:
            - '6653:6653'
            - '9302'
        environment:
            FAUCET_CONFIG_STAT_RELOAD: '${FAUCET_CONFIG_STAT_RELOAD}'
            FAUCET_EVENT_SOCK: '${FAUCET_EVENT_SOCK}'
