apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
        seaplane-label: server
    spec:
      dnsPolicy: Default
      volumes:
      - name: host-mount
        hostPath:
          path: {{ .Values.projectDir }}
      containers:
      - image: seaplane-example
        imagePullPolicy: Never
        name: server
        workingDir: /opt/seaplane
        command: [ "/bin/bash" ]
        args: [ "start.sh" ]
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: host-mount
          mountPath: /opt/seaplane
