routes:
  - name: Google Ads
    categories: [ads]
    routes:
      - www.googleadservices.com/pagead/*
      - adservice.google.com/*
      - "*.googlesyndication.com/pagead/*"

  - name: DoubleClick
    categories: [ads]
    routes:
      - stats.g.doubleclick.net/r/collect
      - cm.g.doubleclick.net/pixel
      - googleads.g.doubleclick.net/*
      - static.doubleclick.net/*
      - ad.doubleclick.net/*

  - name: Google Ads (GoogleTag)
    categories: [stats]
    routes:
      - securepubads.g.doubleclick.net/*
      - www.googletagservices.com/tag/*
    file: doubleclick-pubads.js

  - name: ActiveCampaign
    categories: [stats]
    route: trackcmp.net/visit

  - name: MarkMonitor
    categories: [brand]
    routes:
      - beacon.krxd.net/*
      - cdn.krxd.net/controltag
      - cdn.krxd.net/userdata/*
      - s0.2mdn.net/*

  - name: Gigya
    categories: [auth]
    route: cdns.gigya.com/js/gigya.js
    file: gigya.js

  - name: Google Tag Manager
    categories: [stats]
    route: www.googletagmanager.com/gtm.js
    file: gtm.js

  - name: Zopim Chat
    categories: [chat]
    route: "*.zopim.com/"
    file: zopim.js

  - name: Tealium
    categories: [stats]
    route: tags.tiqcdn.com/utag/*
    file: utag.js

  - name: Visual Web Optimizer
    categories: [abtest]
    route: dev.visualwebsiteoptimizer.com/j.php
    file: vwo.js

  - name: Optimizely
    categories: [abtest]
    route: cdn.optimizely.com/js/*
    file: optimizely.js

  - name: Scorecard Research
    categories: [survey]
    route: sb.scorecardresearch.com/*

  - name: Chartbeat
    categories: [stats]
    routes:
      - static.chartbeat.com/js/*
      - ping.chartbeat.net/ping

  - name: YieldPro/Ancora
    categories: [ads]
    routes:
      - adserving.ancoraplatform.com/*
      - creatives.ancoraplatform.com/*

  - name: JWPlayer
    categories: [stats]
    route: jwpltx.com/*

  - name: Marktplaats
    categories: [stats]
    route: p.marktplaats.net/*

  - name: Google Adsense
    categories: [ads]
    route: www.google.com/adsense/*
    file: adsense.js

  - name: Google Audiences
    categories: [audience]
    route: www.google.com/ads/ga-audiences

  - name: Google Analytics
    categories: [stats]
    routes:
      - www.google-analytics.com/analytics.js
      - www.google-analytics.com/ga.js
    file: analytics.js

  - name: Google Analytics Blocklist
    categories: [stats]
    routes:
      - www.google-analytics.com/plugins/*
      - www.google-analytics.com/__utm.gif

  - name: Google Analytics Measurements
    categories: [stats]
    route: www.google-analytics.com/collect

  - name: YouTube Event Logger
    categories: [stats]
    routes:
      - www.youtube.com/youtubei/v1/log_event
      - www.youtube.com/youtubei/v1/log_interaction
    file: youtube-log-event.json

  - name: YouTube Stats Beacon
    categories: [stats]
    route: www.youtube.com/api/stats/*

  - name: NewRelic
    categories: [mon]
    route: js-agent.newrelic.com/*

  - name: Index Exchange Marketing
    categories: [ads]
    routes:
      - js-sec.indexww.com/*
      - as-sec.casalemedia.com/*

  - name: ArcPublishing
    categories: [stats]
    route: cdn-api.arcpublishing.com/*

  - name: TrustX Advertisement
    categories: [ads]
    route: sofia.trustx.org/*

  - name: Amazon Adsystem
    categories: [ads]
    route: "*.amazon-adsystem.com/*"

  - name: EffectiveMeasure
    categories: [audience]
    routes:
      - "*.effectivemeasure.net/em.js"
      - "*.effectivemeasure.net/html/*"

  - name: Outbrain
    categories: [ads]
    routes:
      - amplifypixel.outbrain.com/pixel
      - widgets.outbrain.com/external/*

  - name: WpDigital
    categories: [stats]
    route: "*.wpdigital.net/metrics*"

  - name: Twitter Analytics
    categories: [stats]
    routes:
      - analytics.twitter.com/*
      - syndication.twitter.com/*

  - name: Hotjar
    categories: [stats]
    route: static.hotjar.com/*
    file: hotjar.js

  - name: Hotjar Block
    categories: [stats]
    route: vars.hotjar.com/*

  - name: Usabila
    categories: [survey]
    route: w.usabilla.com/*

  - name: AdTech
    categories: [ads]
    routes:
      - aka-cdn.adtech.de/*
      - adserver.adtech.de/*

  - name: Google Interactive Media Ads
    categories: [ads]
    route: imasdk.googleapis.com/*

  - name: AppNexus
    categories: [ads]
    route: "*.adnxs.com/*"

  - name: Gravity R&D
    categories: [recommend]
    route: "*.gravityrd-services.com/*"

  - name: Blendle
    categories: [stats]
    route: events.blendle.com/*

  - name: Persgroep Statistics
    categories: [stats]
    route: stats.persgroep.nl/*

  - name: Browserupdate
    categories: [other]
    route: browser-update.org/update.min.js

  - name: TypeKit tracker
    categories: [stats]
    route: p.typekit.net/p.gif

  - name: Facebook
    categories: [social]
    routes:
      - www.facebook.com/plugins/like.php
      - www.facebook.com/plugins/likebox.php
      - www.facebook.com/plugins/page.php
      - connect.facebook.net/*
      - www.facebook.com/tr

  - name: MSN Pixels
    categories: [stats]
    route: "*.msn.com/c.gif"

  - name: Akamai Beacon
    categories: [stats]
    route: "*.akstat.io/*"

  - name: ING Monitor
    categories: [mon]
    route: mon.ingbank.nl/*

  - name: Tucows
    categories: [unknown]
    routes:
      - t.svtrd.com/*
      - tdn.r42tag.com/*

  - name: Vimeo Player Stats
    categories: [stats]
    route: "*.vimeocdn.com/add/player-stats"

  - name: ABTasty (A/B testing)
    categories: [abtest]
    route: try.abtasty.com/*

  - name: BlueConic
    categories: [audience]
    route: cdn.blueconic.net/*

  - name: Lotame (CrowdControl)
    categories: [data]
    route: tags.crwdcntrl.net/*

  - name: Sizmek Advertising Server
    categories: [ads]
    route: "*.serving-sys.com/serving/*"

  - name: Booking.com Tracking
    categories: [stats]
    routes:
      - www.booking.com/js_tracking
      - www.booking.com/navigation_times
      - cexp.booking.com/*
      - q-ak.bstatic.com/speedtest.png

  - name: GroupeSeb International Development
    categories: [stats]
    route: receiver.analytics.groupe-seb.com/events/*

  - name: TagCommander/Commanders ACT
    categories: [stats]
    route: cdn.tagcommander.com/*

  - name: AddToAny
    categories: [share]
    route: static.addtoany.com/*

  - name: Twitter
    categories: [social]
    route: platform.twitter.com/widgets.js

  - name: Google+ PlusOne
    categories: [social]
    route: apis.google.com/js/plusone.js

  - name: OneSignal Push Notifications
    categories: [notify]
    route: cdn.onesignal.com/sdks/OneSignalSDK.js
    file: one-signal-sdk.js

  - name: Atlassian Analytics
    categories: [stats]
    route: analytics.atlassian.com/analytics/events

  - name: Atlassian Cloud Analytics
    categories: [stats]
    route: "*.atlassian.net/rest/analytics/*"

  - name: Google CDN Logging
    categories: [other]
    route: csi.gstatic.com/*

  - name: InterYield
    categories: [virus]
    route: www.ti553.com/*

  - name: Bebi Media Beacon
    categories: [ads]
    routes:
      - trck.bebi.com/*
      - st.bebi.com/*

  - name: Unknown Trackers
    categories: [unknown]
    routes:
      - "*.2mdnsys.com/*"
      - "*.amgload.net/*"
      - "*.piguiqproxy.com/*"
      - "*.smcheck.org/*"
      - 178.175.132.130/script/*

  - name: AdForm Pixel
    categories: [ads]
    route: adx.adform.net/*

  - name: Kisscartoon Ads
    categories: [ads]
    route: ad.kisscartoon.es/*

  - name: OnClick Propeller Ads Media
    categories: [ads]
    route: onclkds.com/*

  - name: Statuspage.io UA
    categories: [stats]
    route: ua.statuspage.io/*

  - name: Bol.com Tracker
    categories: [stats]
    routes:
      - swa.bol.com/*
      - cspreport.bol.com/*
      - "*.bltg.s-bol.com/*"

  - name: Mpulse
    categories: [stats]
    route: "*.go-mpulse.net/*"

  - name: Roblox
    categories: [stats]
    route: ecsv2.roblox.com/www/e.png

  - name: Quantcast Measurement Service
    categories: [audience]
    route: secure.quantserve.com/quant.js

  - name: Stackoverflow Timeout
    categories: [other]
    route: clc.stackoverflow.com/timeout.gif

  - name: AddThis
    categories: [share]
    routes:
      - "*.addthis.com/js/*"
      - m.addthis.com/live/*
      - m.addthisedge.com/live/*

  - name: WatchSeries
    categories: [stats]
    route: dwatchseries.to/show/get-tracking-data

  - name: Ad.nl Advertising
    categories: [ads]
    routes:
      - www.ad.nl/static/sad/js/advertising-*
      - www.ad.nl/static/sad/bva/script/ABC-get.js
      - www.ad.nl/static/sad/bva/script/ABC-place.js

  - name: Google Maps Stats
    categories: [stats]
    route: maps.google.com/maps-api-v3/api/*/stats.js

  - name: Drift
    categories: [chat]
    route: ws.api.drift.com/*
  
  - name: Segment Analytics
    categories: [stats]
    route: cdn.segment.com/analytics.js/*

  - name: Quora Events
    categories: [stats]
    route: "*.quora.com/qevents.js"

  - name: TransIP collect
    categories: [stats]
    routes:
      - ta.transip.net/js/collect.js
      - ta.transip.net/collect

  - name: DuckDuckGo Tracker
    categories: [stats]
    route: duckduckgo.com/t/*

  - name: TradeDoubler
    categories: [click]
    route: clk.tradedoubler.com/click
    handler: click-tracker

  - name: DuckDuckGo
    categories: [click]
    route: duckduckgo.com/y.js
    handler: click-tracker

  - name: Google
    categories: [click]
    routes:
      - www.google.nl/url
      - www.google.be/url
      - www.google.co.uk/url
      - www.google.com/url
    handler: click-tracker

  - name: MailRD
    categories: [click]
    route: click.mailrd.net/*
    handler: click-tracker

  - name: Bit.Ly
    categories: [click]
    route: bit.ly/*
    handler: bit-ly
