
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-26T12:43:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cb84b90a24cc449d00506126cc899b8b5e3ef1cf",
 "version": "v0.1.42"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
