
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "89bb7c651eec191fa3037e20a0c1c41ae802a219",
 "version": "0.8.1b4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
