dist: trusty
sudo: false
language: python

python:
- 2.7
- &latest_py3 3.6

jobs:
  fast_finish: true
  include:
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    install: skip
    script: skip
    deploy:
      provider: pypi
      on:
        tags: true
        all_branches: true
      user: jaraco
      password:
        secure: wP4yjkjjolLH67RrWKO+Eug+l+rn56yXNfJQCmucQxWaPitCWy2GCEbN0ohf8jcIvgkWQUGaPe5caKbP+8VI8Wswnr+whI2ioncvABvldLvhzfIV2pxgEFdOIiCkaDAlAkfDpbFg+h3ixSePF3s5h42oaPpD5ml8mrzvjONNWogmDA3svy/pOTr0P7s7vrRW2ujt3W+pISBFM8rm0YOPO4Mt28dieIz147QZ9ZSUl5quAzUQqMTx+23YDCMrRVxcdmIWjieYFTi0TQXyEUbJVFobPISDXgvJ20tiAKqn5sWZ2jagCyJEipAYn1ATggvcq3Vbg1vtT0VFKXJrwAfzra6Ou5QMFPZrP8a8VELyoJ4cmLY0/G/Jh5CZjyBMFXI7QhGbUERJS0/9KmtXZpDK/z5tae9AvSnneNS5/xb1RnjmnYOq+oM+3lhrSpACo81poxjtxVNcpj6uPYd+yC88qYd2GIFBgnD6WCelwC3iz0zDi3TdUZxusnsn2oO6Un/YNKcmHyofS2C5cj6TZ7efX3BT5w6VeGIgJjUnsjKXNNeXvrjs/MEQj85HZfD7KN2Zbb0LkFgltBdnxzjZZwBmF4i1ziRCGV1KR9y5ftDZ/ve0UQyDTpc17c/FNJu8jsKpmzRTTuaM+BTZOQKt1dnu7XqbsTsRfXSR0/i5n0UDBYc=
      distributions: dists
      skip_cleanup: true
      skip_upload_docs: true
      env:
        - PIP_PRE="true"

cache: pip

install:
- pip install tox tox-venv

script: tox
