---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/swapfile"
  github_url: "https://github.com/debops/ansible-swapfile"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

    - name:  'Robin Schneider'
      email: 'ypid@riseup.net'
      github: 'ypid'

  synopsis: |
    This Ansible role lets you manage one or multiple swap files. You can also
    manage kernel parameters related to how swap is used by the system.

    Note that this role can not setup a swap file on a BTRFS filesystem.

    Refer to [debops.sysctl] for paging and swapping related kernel settings.
    [debops.sysctl]: https://github.com/debops/ansible-sysctl
