
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-03-01T09:09:30+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e87e9a56148ec25fc27713db866587f494b30203",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
