dist: trusty
sudo: false
language: python

python:
- 2.7
- &latest_py3 3.6

jobs:
  fast_finish: true
  include:
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    install: skip
    script: skip
    deploy:
      provider: pypi
      on:
        tags: true
        all_branches: true
      user: jaraco
      password:
        secure: ptWEs1toTgV7DdErUbqIR0Es1fdt+PENuIq/UgYsCrxfH5Iws0MPRMSEUglVEr3z2d4mnuZb+Z72RTMdMqCfFjx4IfSz8RIl4osKsr1S1m34e+K5pqfUGr0uoy5rUGB5sZdV92zdHjAYFFmGygECDrNoyDVa6P5X6A8sTQkZtnBpyW/xGMHMi3im37304SWEhVF4DJPZa2K7hCSomNraNmQR1Ouczq7lNhbabRVtpJ4ewIF7RLc0J+zyDOy6pwIAU8bV34d4jT5VaNgQA9aAYYnBR7rtdO8R0hOwl4DZlrX8n4cHMqDikyYTq4NL1t6DD4BykdQqybza+TEcbMhRc18A7rB4pRz+xG9Sm00zjELW0ARVGN4S+20cgtFNDyA1beAtIaLcfT4AIh4guoJa5UZw8BS+vfn7wN9Y0VD7KXrsxzQ/D8eTcRi3B6XcABAHo+30V7UeVHgp20FHU753aABjkFlzsj7GVIYXkIj4sUDxEtSstjtbo5Q6u3q2gnqXEromZu31ny3JLVFMHxkmyV2jjdIHqFPE8GOzFiYUhQvMOhe01Jm9XWj0eQlwcm23uRo1r16oMfoXtpKXSgEpxoMiVlnjfEil2/fbDfwvpLlnojzseksJmbfttNMBaw2WuFW9sBNiPwteZJzY2ZANO+Wa1kI0JX03ryglrKMOVSA=
      distributions: dists
      skip_cleanup: true
      skip_upload_docs: true

cache: pip

install:
- pip install tox tox-venv

script: tox
