---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/ruby"
  github_url: "https://github.com/debops/ansible-ruby"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    The `debops.ruby` role can be used to configure a Ruby environment. The role
    will install Ruby packages from the current OS release, as well as specified
    Ruby gems, either system-wide or on a selected user account.

