---

ansigenome_info:
  galaxy_url: "https://github.com/debops/ansible-postwhite"
  github_url: "https://github.com/debops/ansible-postwhite"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    The [Postwhite](https://github.com/stevejenkins/postwhite) script can be used
    to generate whitelists and/or blacklists of IP addresses and CIDR subnets based
    on the SPF records of selected domains. These whitelists/blacklists can then be
    used by the [Postscreen](http://www.postfix.org/POSTSCREEN_README.html)
    Postfix service to automatically allow or deny connections to specific SMTP
    clients. This is useful for accepting messages from big mail providers like
    Google and Outlook which may resend mail messages from different IP addresses,
    which in turn interferes with Postscreen SMTP client greylisting.

    The `debops.postwhite` Ansible role will install Postwhite script and
    configure Postfix automatically using the `debops.postfix` Ansible role, as long
    as the Postscreen configuration is enabled by the `debops.postscreen` role.
    See the documentation of the mentioned roles for more details.
