---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/apt_install"
  github_url: "https://github.com/debops/ansible-apt_install"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

    - name:  'Robin Schneider'
      url: 'http://ypid.de/'
      email: 'ypid@riseup.net'
      twitter: 'ypid'
      github: 'ypid'

  synopsis: |
    The `debops.apt_install` Ansible role is meant to be used as an easy way to
    install APT packages on hosts that don't require more extensive
    configuration which would require a more extensive, custom Ansible role.
    The role itself exposes several Ansible default variables which can be used
    to specify custom lists of packages on different levels of Ansible
    inventory (global, per-group or per-host).

