---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/netbox"
  github_url: "https://github.com/debops/ansible-netbox"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    [NetBox](https://github.com/digitalocean/netbox/) is an IP address management
    (IPAM) and data center infrastructure management (DCIM) application developed
    by [DigitalOcean](https://digitalocean.com/).
