---
name: denoising_conv_autoencoder_mnsit
output_dir: "/tmp/polyaxon_logs/denoising_conv_autoencoder"
train_steps_per_iteration: 1000
run_config:
  save_checkpoints_steps: 1000
train_input_data_config:
  pipeline_config:
    module: TFRecordImagePipeline
    batch_size: 64
    num_epochs: 5
    shuffle: true
    dynamic_pad: false
    params:
      data_files: "../data/mnist/mnist_train.tfrecord"
      meta_data_file: "../data/mnist/meta_data.json"
    definition:
      image:
      - - Standardization
        - {}
      - - GaussianNoise
        - scale: 0.5
eval_input_data_config:
  pipeline_config:
    module: TFRecordImagePipeline
    batch_size: 32
    num_epochs: 1
    shuffle: true
    dynamic_pad: false
    params:
      data_files: "../data/mnist/mnist_eval.tfrecord"
      meta_data_file: "../data/mnist/meta_data.json"
    definition:
      image:
      - - Standardization
        - {}
estimator_config:
  output_dir: "/tmp/polyaxon_logs/denoising_conv_autoencoder"
model_config:
  summaries:
  - loss
  - image_input
  - image_result
  module: Generator
  optimizer_config:
    module: adadelta
    learning_rate: 0.9
  encoder_config:
    definition:
    - - Conv2d
      - num_filter: 32
        filter_size: 3
        strides: 1
        activation: relu
        regularizer: l2_regularizer
    - - MaxPool2d
      - kernel_size: 2
    - - Conv2d
      - num_filter: 32
        filter_size: 3
        activation: relu
        regularizer: l2_regularizer
    - - MaxPool2d
      - kernel_size: 2
  decoder_config:
    definition:
    - - Conv2d
      - num_filter: 32
        filter_size: 3
        strides: 1
        activation: relu
        regularizer: l2_regularizer
    - - Upsample2d
      - kernel_size: 2
    - - Conv2d
      - num_filter: 32
        filter_size: 3
        activation: relu
        regularizer: l2_regularizer
    - - Upsample2d
      - kernel_size: 2
    - - Conv2d
      - num_filter: 1
        filter_size: 3
        activation: relu
        regularizer: l2_regularizer
