---
version: 1

project:
  name: lenet_mnsit

settings:
  logging:
    level: INFO
  run_type: local

environment:
  run_config:
    save_summary_steps: 100
    save_checkpoints_steps: 100

model:
  classifier:
    loss:
      MeanSquaredError:
    optimizer:
      Adam:
        learning_rate: 0.007
        decay_type: exponential_decay
        decay_rate: 0.2
    metrics:
      - TruePositives
      - TrueNegatives
      - FalsePositives
      - FalseNegatives
      - Recall
      - AUC
      - Accuracy
      - Precision
    one_hot_encode: true
    n_classes: 10
    graph:
      input_layers: image
      layers:
        - Conv2D:
            filters: 32
            kernel_size: 5
            strides: 1
        - MaxPooling2D:
            pool_size: 2
        - Conv2D:
            filters: 64
            kernel_size: 5
        - MaxPooling2D:
            pool_size: 2
        - Flatten:
        - Dense:
            units: 1024
            activation: tanh
        - Dense:
           units: 10

train:
  train_steps: 100
  data_pipeline:
    TFRecordImagePipeline:
      batch_size: 64
      num_epochs: 1
      shuffle: true
      data_files: ["../data/mnist/mnist_train.tfrecord"]
      meta_data_file: "../data/mnist/meta_data.json"
      feature_processors:
        image:
          input_layers: [image]
          layers:
            - Cast:
                dtype: float32

eval:
  data_pipeline:
    TFRecordImagePipeline:
      batch_size: 32
      num_epochs: 1
      shuffle: False
      data_files: ["../data/mnist/mnist_eval.tfrecord"]
      meta_data_file: "../data/mnist/meta_data.json"
      feature_processors:
        image:
          input_layers: [image]
          layers:
            - Cast:
                dtype: float32
