---
name: vae_mnsit
output_dir: "/tmp/polyaxon_logs/vae"
train_steps_per_iteration: 100
run_config:
  save_checkpoints_steps: 100
train_input_data_config:
  pipeline_config:
    module: TFRecordImagePipeline
    batch_size: 64
    num_epochs: 5
    shuffle: true
    dynamic_pad: false
    params:
      data_files: "../data/mnist/mnist_train.tfrecord"
      meta_data_file: "../data/mnist/meta_data.json"
    definition:
      image:
      - - Standardization
        - {}
      - - Reshape
        - new_shape:
          - 784
eval_input_data_config:
  pipeline_config:
    module: TFRecordImagePipeline
    batch_size: 32
    num_epochs: 1
    shuffle: true
    dynamic_pad: false
    params:
      data_files: "../data/mnist/mnist_eval.tfrecord"
      meta_data_file: "../data/mnist/meta_data.json"
    definition:
      image:
      - - Standardization
        - {}
      - - Reshape
        - new_shape:
          - 784
estimator_config:
  output_dir: "/tmp/polyaxon_logs/vae"
model_config:
  module: Generator
  summaries:
  - loss
  optimizer_config:
    module: adadelta
    learning_rate: 0.9
  encoder_config:
    definition:
    - - FullyConnected
      - num_units: 128
    - - FullyConnected
      - num_units: 256
  decoder_config:
    definition:
    - - FullyConnected
      - num_units: 256
    - - FullyConnected
      - num_units: 784
  bridge_config:
    module: LatentBridge
