---

ansigenome_info:
  galaxy_url: "https://github.com/debops/ansible-ansible_plugins"
  github_url: "https://github.com/debops/ansible-ansible_plugins"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    Ansible can be extended in various ways by the use of [custom plugins](https://docs.ansible.com/ansible/latest/dev_guide/developing_plugins.html).
    This role contains a set of custom Ansible plugins used by various DebOps
    roles. The plugins are enabled by including this role as a dependency of
    another role.
