---

- name: Make sure Ansible build directory exists
  file:
    path: '{{ debops__ansible_git_build_dir }}'
    state: 'directory'
    owner: '{{ debops__ansible_git_become_user }}'
    group: 'root'
    mode: '0755'
  when: debops__ansible_git|bool

- name: Bootstrap Ansible from source
  script: 'script/bootstrap-ansible.sh "{{ debops__ansible_git_branch }}" "{{ debops__ansible_git_build_dir }}"'
  become_user: '{{ debops__ansible_git_become_user }}'
  register: debops__register_bootstrap
  when: debops__ansible_git|bool
  changed_when: debops__register_bootstrap.stdout != ""

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - [ 'git', 'python-pip' ]
    - '{{ debops__base_packages }}'
    - '{{ debops__ansible_packages }}'
    - '{{ debops__packages }}'
  when: item|d()

- name: Install DebOps from PyPI
  pip:
    name: '{{ item }}'
    state: 'present'
  with_items: '{{ debops__pip_packages }}'
  notify: '{{ [ "Update DebOps in the background with " + debops__update_method ] if not debops__update_method == "sync" else omit }}'
  when: item|d()

- name: Configure system-wide DebOps scripts
  template:
    src: 'etc/debops.cfg.j2'
    dest: '/etc/debops.cfg'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: debops__install_systemwide|bool

- name: Update roles and playbooks
  become: '{{ debops__install_systemwide|bool }}'
  command: debops-update
  when: debops__update_method == 'sync'

- name: Clone project repository
  become: '{{ debops__install_systemwide|bool }}'
  git:
    repo: '{{ debops__project_git_repo }}'
    dest: '{{ debops__project_name if debops__project_name else debops__project_git_repo | basename }}'
    update: True
  when: debops__project_git_repo

- name: Initialize new project
  become: '{{ debops__install_systemwide|bool }}'
  command: debops-init '{{ debops__project_name }}'
  args:
    creates: '{{ debops__project_name }}/.debops.cfg'
  when: debops__project_name|d() and
        not debops__project_git_repo
