# coding: utf-8

"""
    Flip API

    Description  # noqa: E501

    OpenAPI spec version: 2.0.1
    Contact: cloudsupport@telestream.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import telestream_cloud_flip
from telestream_cloud_flip.models.paginated_profiles_collection import PaginatedProfilesCollection  # noqa: E501
from telestream_cloud_flip.rest import ApiException


class TestPaginatedProfilesCollection(unittest.TestCase):
    """PaginatedProfilesCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedProfilesCollection(self):
        """Test PaginatedProfilesCollection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = telestream_cloud_flip.models.paginated_profiles_collection.PaginatedProfilesCollection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
