---

dist: 'trusty'
sudo: True
language: 'python'
python: '2.7'

virtualenv:
  system_site_packages: true

before_install: True
install: True

script:
  - 'git clone --depth 1 https://github.com/nickjj/rolespec'
  - 'cd rolespec ; bin/rolespec -r https://github.com/debops/test-suite ; cd -'

  # We know the scripts are not perfect. Please don’t add more things that shellcheck v0.4.4 will complain about!
  # The shellcheck and jq command one-liner does not return with a non-zero exit code when the tested file does not exist.
  - 'test -r ./files/secret/pki/lib/pki-authority'
  - 'shellcheck --format=json ./files/secret/pki/lib/pki-authority | jq --exit-status "(. | length) <= 48"'
  - 'test -r ./files/usr/local/lib/pki/pki-realm'
  - 'shellcheck --format=json ./files/usr/local/lib/pki/pki-realm  | jq --exit-status "(. | length) <= 83"'

notifications:
  webhooks:
    - 'https://galaxy.ansible.com/api/v1/notifications/'
