
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-16T13:25:30-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "2cd7e7e8850e3edf616da406e9a5f03969cd96f1",
 "version": "3.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
