---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/kibana"
  github_url: "https://github.com/debops/ansible-kibana"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    [Kibana](https://en.wikipedia.org/wiki/Kibana) is a web-based dashboard which
    can be used to display and analyze data stored in an Elasticsearch cluster. It
    is a part of the Elasticsearch, Logstash, Kibana (ELK) stack. The software is
    developed by [Elastic](https://elastic.co/).
    
    The `debops.kibana` Ansible role can be used to deploy Kibana behind an
    `nginx` reverse proxy which connects to a local or remote Elasticsearch
    cluster. The role can be used as a dependency by other Ansible roles to allow
    control over their configuration options in the Kibana configuration file.
