- project:
    check:
      jobs:
        - sushy-tools-tempest-dsvm-ironic-ipa-partition-redfish-src
        - build-openstack-sphinx-docs
    gate:
      jobs:
        - sushy-tools-tempest-dsvm-ironic-ipa-partition-redfish-src
        - build-openstack-sphinx-docs
