# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-19 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A0User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.CharField(db_index=True, max_length=140, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=140, null=True)),
                ('email', models.EmailField(max_length=140)),
                ('email_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
