---

- name: Manage Linux kernel modules
  hosts: [ 'debops_service_kernel_module' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops-contrib.kernel_module
      tags: [ 'role::kernel_module' ]
