---

ansigenome_info:
  galaxy_url: 'https://galaxy.ansible.com/debops-contrib/firejail'
  github_url: 'https://github.com/debops-contrib/ansible-firejail'
  git_branch: 'master'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Robin Schneider'
      email: 'ypid@riseup.net'
      github: 'ypid'

  synopsis: |
    Firejail is a SUID program that reduces the risk of security breaches by
    restricting the running environment of untrusted applications using Linux
    namespaces and seccomp-bpf.

    This Ansible role allows you to setup and configure Firejail.

    ### Features

    * Install Firejail from jessie-backports or other configured APT
      repositories. [debops.apt] can be used to enable Backports if needed.
    * Sandbox programs system wide by placing a symlink to `firejail` into the
      ``PATH`` so that `firejail` can wrap program invocations and sandbox the
      invoked program using security profiles that Firejail ships or that the system
      administrator defines.

    [debops.apt]: https://github.com/debops/ansible-apt
