# Conda environment for Gammapy development
name: gammapy-dev

channels:
  - conda-forge
  - sherpa

dependencies:
  - python==3.6
  - cython
  - numpy
  - astropy
  - regions
  - click
  - pyyaml
  - scipy
  - matplotlib
  - scikit-image
  - uncertainties
  - healpy
  - reproject
  - sherpa
  - pytest
  - sphinx
  - aplpy
  - ipython
  - pandoc
  - pip:
    - nbsphinx==0.2.17
    - sphinx-click
