- project:
    check:
      jobs:
        - networking-odl-grenade:
            voting: false
            branches: ^(?!(driverfixes|stable/(mitaka|newton))).*$
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-tempest-carbon
        - networking-odl-tempest-nitrogen
        - networking-odl-tempest-oxygen
        - networking-odl-tempest-carbon-multinode:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-tempest-nitrogen-multinode:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-tempest-oxygen-multinode:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-rally-carbon:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-rally-nitrogen:
            branches: ^(?!stable/(newton|ocata)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-rally-oxygen:
            voting: false
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-fullstack-carbon:
            branches: ^(?!stable/(newton|ocata)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-functional-carbon:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-fullstack-nitrogen:
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-functional-nitrogen:
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-fullstack-oxygen:
            voting: false
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-functional-oxygen:
            voting: false
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
    gate:
      jobs:
        - networking-odl-rally-carbon:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-rally-nitrogen:
            branches: ^(?!stable/(newton|ocata)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-fullstack-carbon:
            branches: ^(?!stable/(newton|ocata)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-functional-carbon:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-fullstack-nitrogen:
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-functional-nitrogen:
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
