
build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.14"
      PYTHON_ARCH: "32"
      TOX_ENV: "py27"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.4"
      PYTHON_ARCH: "32"
      TOX_ENV: "py34"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.3"
      PYTHON_ARCH: "32"
      TOX_ENV: "py35"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.3"
      PYTHON_ARCH: "32"
      TOX_ENV: "py36"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install pip --user --upgrade"
  - "%PYTHON%/Scripts/pip.exe install -r requirements-dev.txt"
  - "%PYTHON%/Scripts/pip.exe install --editable . --user"

test_script:
  - "%PYTHON%/Scripts/flake8.exe"
  - "%PYTHON%/Scripts/pylint.exe curver.kernel"
  - "%PYTHON%/Scripts/tox.exe -e %TOX_ENV% -- --hypothesis-profile=ci"

