
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-09T20:11:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c80dbec00502e597968877ad3301faef30ce0eb9",
 "version": "2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
