
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-14T23:41:08-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6b6154bc29d295584af2688ba7fac77eac217723",
 "version": "0.10.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
