language: python
python:
  - "3.6"

sudo: false

cache: pip

install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements.txt -e .

script:
  - py.test --cov=. docker_easyenroll
  - flake8 docker_easyenroll

after_success:
  - codecov
