
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-27T18:47:24-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "940fea09c68a50ed36622c74d7ba4ce6e5e16baa",
 "version": "1.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
