language: python
python:
  - "2.6"
  - "2.7" 
  - "3.3"
  - "3.4" 
  - "3.5"
  - "3.6"
  - "3.6-dev"  
  - "3.7-dev"  
  - "nightly"

# matrix:
#   fast_finish: true

env:
  matrix:
    - CUDA_VERSION_MAJOR="8" CUDA_VERSION_MINOR="0" CUDA_PKG_LONGVERSION="${CUDA_VERSION_MAJOR}.${CUDA_VERSION_MINOR}.61-1" CUDA_PKG_VERSION="${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR}"
 
 install:
  - CUDA_REPO_PKG=cuda-repo-ubuntu1404_${CUDA_PKG_LONGVERSION}_amd64.deb
  - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/$CUDA_REPO_PKG
  - sudo dpkg -i $CUDA_REPO_PKG
  - rm $CUDA_REPO_PKG
  - sudo apt-get -y update
  - sudo apt-get install -y --no-install-recommends  cuda-core-$CUDA_PKG_VERSION  cuda-cudart-dev-$CUDA_PKG_VERSION  cuda-cublas-dev-$CUDA_PKG_VERSION cuda-curand-dev-$CUDA_PKG_VERSION
  - sudo ln -s /usr/local/cuda-${CUDA_VERSION_MAJOR}.${CUDA_VERSION_MINOR} /usr/local/cuda
  - pip install --upgrade pip
  - pip install --ignore-installed setuptools
  - pip install --ignore-installed wheel
  - pip install --ignore-installed pytest-cov
  - pip install --ignore-installed pytest
  - pip install -e .

script:
  - python -c "import farneback3d"
  - pytest # or py.test for Python versions 3.5 and below

os:
  - linux
  # - osx

# addons:
#   apt:
#     packages:
