PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "django_geo_db_state" ("state_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "abbreviation" varchar(2) NOT NULL UNIQUE, "generated_name" varchar(50) NULL, "country_id" integer NOT NULL REFERENCES "django_geo_db_country" ("country_id"), "geocoordinate_id" integer NOT NULL REFERENCES "django_geo_db_geocoordinate" ("geocoordinate_id"), "name" varchar(50) NOT NULL);
INSERT INTO "django_geo_db_state" VALUES(1,'AL','Alabama, US',222,235,'Alabama');
INSERT INTO "django_geo_db_state" VALUES(2,'AK','Alaska, US',222,236,'Alaska');
INSERT INTO "django_geo_db_state" VALUES(3,'AZ','Arizona, US',222,237,'Arizona');
INSERT INTO "django_geo_db_state" VALUES(4,'AR','Arkansas, US',222,238,'Arkansas');
INSERT INTO "django_geo_db_state" VALUES(5,'AS','American Samoa, US',222,239,'American Samoa');
INSERT INTO "django_geo_db_state" VALUES(6,'CA','California, US',222,240,'California');
INSERT INTO "django_geo_db_state" VALUES(7,'CO','Colorado, US',222,241,'Colorado');
INSERT INTO "django_geo_db_state" VALUES(8,'CT','Connecticut, US',222,242,'Connecticut');
INSERT INTO "django_geo_db_state" VALUES(9,'DE','Delaware, US',222,243,'Delaware');
INSERT INTO "django_geo_db_state" VALUES(10,'DC','District of Columbia, US',222,244,'District of Columbia');
INSERT INTO "django_geo_db_state" VALUES(11,'FL','Florida, US',222,245,'Florida');
INSERT INTO "django_geo_db_state" VALUES(12,'FM','Federated States Of Micronesia, US',222,246,'Federated States Of Micronesia');
INSERT INTO "django_geo_db_state" VALUES(13,'GA','Georgia, US',222,247,'Georgia');
INSERT INTO "django_geo_db_state" VALUES(14,'GU','Guam, US',222,248,'Guam');
INSERT INTO "django_geo_db_state" VALUES(15,'HI','Hawaii, US',222,249,'Hawaii');
INSERT INTO "django_geo_db_state" VALUES(16,'ID','Idaho, US',222,250,'Idaho');
INSERT INTO "django_geo_db_state" VALUES(17,'IL','Illinois, US',222,251,'Illinois');
INSERT INTO "django_geo_db_state" VALUES(18,'IN','Indiana, US',222,252,'Indiana');
INSERT INTO "django_geo_db_state" VALUES(19,'IA','Iowa, US',222,253,'Iowa');
INSERT INTO "django_geo_db_state" VALUES(20,'KS','Kansas, US',222,254,'Kansas');
INSERT INTO "django_geo_db_state" VALUES(21,'KY','Kentucky, US',222,255,'Kentucky');
INSERT INTO "django_geo_db_state" VALUES(22,'LA','Louisiana, US',222,256,'Louisiana');
INSERT INTO "django_geo_db_state" VALUES(23,'ME','Maine, US',222,257,'Maine');
INSERT INTO "django_geo_db_state" VALUES(24,'MH','Marshall Islands, US',222,258,'Marshall Islands');
INSERT INTO "django_geo_db_state" VALUES(25,'MP','Northern Mariana Islands, US',222,259,'Northern Mariana Islands');
INSERT INTO "django_geo_db_state" VALUES(26,'MT','Montana, US',222,260,'Montana');
INSERT INTO "django_geo_db_state" VALUES(27,'NE','Nebraska, US',222,261,'Nebraska');
INSERT INTO "django_geo_db_state" VALUES(28,'NV','Nevada, US',222,262,'Nevada');
INSERT INTO "django_geo_db_state" VALUES(29,'NH','New Hampshire, US',222,263,'New Hampshire');
INSERT INTO "django_geo_db_state" VALUES(30,'NJ','New Jersey, US',222,264,'New Jersey');
INSERT INTO "django_geo_db_state" VALUES(31,'NM','New Mexico, US',222,265,'New Mexico');
INSERT INTO "django_geo_db_state" VALUES(32,'NY','New York, US',222,266,'New York');
INSERT INTO "django_geo_db_state" VALUES(33,'NC','North Carolina, US',222,267,'North Carolina');
INSERT INTO "django_geo_db_state" VALUES(34,'ND','North Dakota, US',222,268,'North Dakota');
INSERT INTO "django_geo_db_state" VALUES(35,'OH','Ohio, US',222,269,'Ohio');
INSERT INTO "django_geo_db_state" VALUES(36,'OK','Oklahoma, US',222,270,'Oklahoma');
INSERT INTO "django_geo_db_state" VALUES(37,'OR','Oregon, US',222,271,'Oregon');
INSERT INTO "django_geo_db_state" VALUES(38,'MD','Maryland, US',222,272,'Maryland');
INSERT INTO "django_geo_db_state" VALUES(39,'MA','Massachusetts, US',222,273,'Massachusetts');
INSERT INTO "django_geo_db_state" VALUES(40,'MI','Michigan, US',222,274,'Michigan');
INSERT INTO "django_geo_db_state" VALUES(41,'MN','Minnesota, US',222,275,'Minnesota');
INSERT INTO "django_geo_db_state" VALUES(42,'MS','Mississippi, US',222,276,'Mississippi');
INSERT INTO "django_geo_db_state" VALUES(43,'MO','Missouri, US',222,277,'Missouri');
INSERT INTO "django_geo_db_state" VALUES(44,'PA','Pennsylvania, US',222,278,'Pennsylvania');
INSERT INTO "django_geo_db_state" VALUES(45,'PW','Palau, US',222,279,'Palau');
INSERT INTO "django_geo_db_state" VALUES(46,'RI','Rhode Island, US',222,280,'Rhode Island');
INSERT INTO "django_geo_db_state" VALUES(47,'PR','Puero Rico, US',222,281,'Puero Rico');
INSERT INTO "django_geo_db_state" VALUES(48,'SC','South Carolina, US',222,282,'South Carolina');
INSERT INTO "django_geo_db_state" VALUES(49,'SD','South Dakota, US',222,283,'South Dakota');
INSERT INTO "django_geo_db_state" VALUES(50,'TN','Tennessee, US',222,284,'Tennessee');
INSERT INTO "django_geo_db_state" VALUES(51,'TX','Texas, US',222,285,'Texas');
INSERT INTO "django_geo_db_state" VALUES(52,'UT','Utah, US',222,286,'Utah');
INSERT INTO "django_geo_db_state" VALUES(53,'VT','Vermont, US',222,287,'Vermont');
INSERT INTO "django_geo_db_state" VALUES(54,'VA','Virginia, US',222,288,'Virginia');
INSERT INTO "django_geo_db_state" VALUES(55,'VI','Saint Thomas, US',222,289,'Saint Thomas');
INSERT INTO "django_geo_db_state" VALUES(56,'WA','Washington, US',222,290,'Washington');
INSERT INTO "django_geo_db_state" VALUES(57,'WV','West Virginia, US',222,291,'West Virginia');
INSERT INTO "django_geo_db_state" VALUES(58,'WI','Wisconsin, US',222,292,'Wisconsin');
INSERT INTO "django_geo_db_state" VALUES(59,'WY','Wyoming, US',222,293,'Wyoming');
CREATE UNIQUE INDEX "django_geo_db_state_country_id_a564ed4b_uniq" ON "django_geo_db_state" ("country_id", "name");
CREATE INDEX "django_geo_db_state_93bfec8a" ON "django_geo_db_state" ("country_id");
CREATE INDEX "django_geo_db_state_c2ff64a1" ON "django_geo_db_state" ("geocoordinate_id");
COMMIT;
