# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ava_engine/ava/service_model_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ava_engine.ava import api_model_sync_pb2 as ava__engine_dot_ava_dot_api__model__sync__pb2
from ava_engine.ava import api_model_load_pb2 as ava__engine_dot_ava_dot_api__model__load__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ava_engine/ava/service_model_api.proto',
  package='ava_engine',
  syntax='proto3',
  serialized_pb=_b('\n&ava_engine/ava/service_model_api.proto\x12\nava_engine\x1a#ava_engine/ava/api_model_sync.proto\x1a#ava_engine/ava/api_model_load.proto2\x97\x01\n\x0bModelApiDef\x12\x43\n\x04Sync\x12\x1c.ava_engine.ModelSyncRequest\x1a\x1d.ava_engine.ModelSyncResponse\x12\x43\n\x04Load\x12\x1c.ava_engine.ModelLoadRequest\x1a\x1d.ava_engine.ModelLoadResponseb\x06proto3')
  ,
  dependencies=[ava__engine_dot_ava_dot_api__model__sync__pb2.DESCRIPTOR,ava__engine_dot_ava_dot_api__model__load__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MODELAPIDEF = _descriptor.ServiceDescriptor(
  name='ModelApiDef',
  full_name='ava_engine.ModelApiDef',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=129,
  serialized_end=280,
  methods=[
  _descriptor.MethodDescriptor(
    name='Sync',
    full_name='ava_engine.ModelApiDef.Sync',
    index=0,
    containing_service=None,
    input_type=ava__engine_dot_ava_dot_api__model__sync__pb2._MODELSYNCREQUEST,
    output_type=ava__engine_dot_ava_dot_api__model__sync__pb2._MODELSYNCRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Load',
    full_name='ava_engine.ModelApiDef.Load',
    index=1,
    containing_service=None,
    input_type=ava__engine_dot_ava_dot_api__model__load__pb2._MODELLOADREQUEST,
    output_type=ava__engine_dot_ava_dot_api__model__load__pb2._MODELLOADRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODELAPIDEF)

DESCRIPTOR.services_by_name['ModelApiDef'] = _MODELAPIDEF

# @@protoc_insertion_point(module_scope)
