# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2017 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it under the
# terms of the MIT License; see LICENSE file for more details.
#
# In applying this license, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

addons:
  chrome: stable # https://docs.travis-ci.com/user/chrome

dist: trusty # Chrome driver fails if not trusty dist

notifications:
  email: false

# Chrome Webdriver fails if not on sudo
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: true

language: python

matrix:
  fast_finish: true

cache:
  - pip

env:
  global:
    - E2E_OUTPUT=base64
    - ES_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.4.tar.gz
  matrix:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release DEPLOY=true
  - REQUIREMENTS=devel

python:
  - "2.7"
  - "3.5"

before_install:
  # Download and start ES
  - "mkdir /tmp/elasticsearch"
  - "wget -O - $ES_URL | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/elasticsearch &"
  # Chrome webdriver for Selenium
  - "PATH=$PATH:$HOME/webdrivers"
  - "if [ ! -f $HOME/webdrivers/chromedriver ]; then wget https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip -P $HOME/webdrivers; unzip -d $HOME/webdrivers $HOME/webdrivers/chromedriver_linux64.zip; fi"
  # Install packages
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e all --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e all --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder -e all --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"

before_script:
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Allow ES and xvfb to start
  - "sleep 10"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: inveniosoftware
  password:
    secure: TODO:PYPISECUREHASH
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "3.5"
    repo: inveniosoftware/pytest-invenio
    condition: $DEPLOY = true
