language: python
addons:
  apt:
    packages:
    - gdal-bin
    - libgdal-dev
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install .
- pip install xarray dask toolz rasterio==1.0a12
- pip install coveralls
script: coverage run --source=trollimage setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: Martin.Raspaud
  password:
    secure: RuQzdaLTY4sryIzG8Hz1KWEsyYRxrLvbyfm7DurXDPcj2vsujRwJicNwBrJajIBkzZWwdmWE8db55BPWZwCsJtVUbE53vc742wSAcci2zzCgizSb/jjlDkwk1CE/PoMl4t3JsuIU6bklgw1Y1d4Xn4+BeZe8Blol5PD/FUovxfo=
  on:
    tags: true
    repo: pytroll/trollimage
sudo: false
notifications:
  slack: pytroll:96mNSYSI1dBjGyzVXkBT6qFt
