
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-17T13:47:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "06fddaa79b323c93bf02abb506c74015d3d4ac61",
 "version": "0.4.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
