
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-03-06T17:59:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b5c9b36f8954579b797b5794c0c2365c7fe32a77",
 "version": "v0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
