---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/java"
  github_url: "https://github.com/debops/ansible-java"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Nick Janetakis'
      url: ''
      email: 'nick.janetakis@gmail.com'
      twitter: 'nickjanetakis'
      github: 'nickjj'

  synopsis: |
    The `debops.java` Ansible role installs the default Java OpenJRE headless
    packages for current OS release. It can also be used to install other Java or
    OpenJDK/OpenJRE versions.
