---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/root_account"
  github_url: "https://github.com/debops/ansible-root_account"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Fabio Bonelli'
      email: 'fabio@fabiobonelli.it'
      twitter: ''
      github: 'bfabio'

  synopsis: |
    The `debops.root_account` Ansible role can be used to manage the system root
    account and generate SSH private keys for use on other hosts.
