language: python
sudo: false
os:
- linux
python:
- '2.7'
- '3.5'
- '3.6'
- 3.7-dev
matrix:
  allow_failures:
  - python: 3.7-dev
install:
- pip install -U pip
- pip install -U setuptools
- pip install -U tox
- pip install -U tox-travis
- pip install python-coveralls
script:
- tox -v --recreate
after_success:
- coveralls
deploy:
  provider: pypi
  user: levinoecker
  password:
    secure: Bz7Bu0cBzUUfJhGOMVfVK55HFvQ8czQJsfBHbox/7P51RSfFh1+yn7czosLSboVJoiVx0tBv5jp5gjFljPhQV0Qvawj8Iw3BC/EEAajrmNriF9ZSRFkwcJ+7ziAv3uiasuweUXA63/T8J/GnAB/hyzB1yspoExaCthwSvZnY4jiUNorfPuPDDQCMP5OSl7gtvCjfcEbeERfrdHePD/L83Z8z6GcmtaRaBBBOHFspUbQEY5pNGXfnXDhNhxYmNF+desraObdURB0b9A/sEX0hbAlb+zn4uhkVfn7+M8DYc4B1iP5ngWnX1b26/WzAGDASkOqS3JMLABCQaLBYenbVWuzRdj+/T26GlbWlKfTZhV8weMtXIx5sJrXdWuFv5Hl+c+j24jCN2eJXqAvDkSbSfFlj3zo7DjPfRnq5UkmPLSuOoJyDQrN+gEejXR8Ea6JoFQlp7dM6QeJZtWo15HCJ3diiz7VqfTUMyXbi/sY9aOKdpKKiym4A1EEkMron0OY8tnzAGptTWqez6Q55Mi5DXvUgrhkFzuZrFjcHTNKnPW2S4yb02szBtKQivJb4ePwoO8+Mf21q/LPrqz2dvdx9cC8QbhZP9e2Egr+2WJvPHGUWSWey5X+PIymnRtJCIZGkMaNweeanHssHFYAONuSDHXnBmnIoHWqqs81AM8GtUjo=
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true
    python: '3.6'
