# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='language',
            field=models.CharField(choices=[(b'ar', 'Arabe'), (b'cn', 'Chines'), (b'en', 'English'), (b'pt', 'Portugu\xeas'), (b'es', 'Espanhol'), (b'ru', 'Russia')], max_length=5),
        ),
        migrations.AlterField(
            model_name='state',
            name='language',
            field=models.CharField(choices=[(b'ar', 'Arabe'), (b'cn', 'Chines'), (b'en', 'English'), (b'pt', 'Portugu\xeas'), (b'es', 'Espanhol'), (b'ru', 'Russia')], max_length=5),
        ),
    ]
