"""
AUTOGENERATED by git post-commit hook. Note that these are always from the PREVIOUS commit, and so may be out of date by one log entry
"""
git_branch    = "master"
git_shorthash = "26e0269"
git_longhash  = "26e0269ed2a2c370f45810522ac9cb47da033519"
git_last_tag  = "0.9.0.rc1"
