---

ansigenome_info:
  galaxy_url: 'https://galaxy.ansible.com/debops/owncloud'
  github_url: 'https://github.com/debops/ansible-owncloud'
  git_branch: 'master'

  travis: True

  authors:
    - name:  'Maciej Delmanowski'
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

    - name:  'Hartmut Goebel'
      url: 'http://www.crazy-compilers.com/'
      email: 'h.goebel@crazy-compilers.com'
      github: 'htgoebel'

    - name:  'Robin Schneider'
      email: 'ypid@riseup.net'
      github: 'ypid'

  synopsis: |
    This role installs a [ownCloud](https://owncloud.org/) instance on a
    specified host, either with SQLite, MySQL, MariaDB or PostgreSQL database
    as a backend and an nginx webserver as a frontend.

    Note that Nginx is
    [not officially supported by ownCloud nor NextCloud](https://github.com/debops/ansible-owncloud/issues/49)
    but it is community supported and should work without problems.
    Apache is supported by the role but not yet used by default.

    ### Features

    * LDAP setup.
    * In memory caching using Redis for file locking and APCu.
    * ownCloud theming support.
    * Extensive configuration options via Ansible’s inventory.
    * Fully automated ownCloud security updates. [Not yet enabled by default](https://github.com/debops/ansible-owncloud/issues/28).
