---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/golang"
  github_url: "https://github.com/debops/ansible-golang"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Nick Janetakis'
      url: ''
      email: 'nick.janetakis@gmail.com'
      twitter: 'nickjanetakis'
      github: 'nickjj'

    - name: 'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    The `debops.golang` role can be used to setup a Go environment using
    Debian/Ubuntu packages. It uses `debops.apt_preferences` role to
    automatically install backported Go packages on older OS releases.

