---

ansigenome_info:
  galaxy_url: 'https://galaxy.ansible.com/debops/rsyslog'
  github_url: 'https://github.com/debops/ansible-rsyslog'
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    The [rsyslog](http://rsyslog.com/) package is used to read, process, store
    and forward system logs in different ways, on local or remote systems. The
    `debops.rsyslog` role can be used to easily configure log forwarding to
    a central log server, as well as store logs on the filesystem or other storage
    backends.
