language: cpp
matrix:
  include:
  - compiler: clang
    os: linux
    dist: trusty
    sudo: required
    group: edge
  - compiler: gcc
    os: linux
    dist: trusty
    sudo: required
    group: edge
  - compiler: clang
    os: osx
    osx_image: xcode8.1
  - compiler: gcc
    os: osx
    osx_image: xcode8.1
install:
  - if test ${TRAVIS_OS_NAME} = "linux"; then sudo apt-get install -y libcppunit-dev; fi
  - ./bootstrap
script:
  - ./configure && make && make check
