# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/

sudo: true
language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    # - DISTRIB="ubuntu" PYTHON_VERSION="2.7" COVERAGE="true"  # ipython 6.0 install fails, must install LTS release 5.0 for 2.7
    # - DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="false"
    # - DISTRIB="conda" PYTHON_VERSION="3.4" COVERAGE="false"
    - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="false"
    - DISTRIB="ubuntu" PYTHON_VERSION="3.5" COVERAGE="false"
addons:
  apt:
    packages:
      - git
      - python3-pip
      - gfortran
      - libopenblas-dev
      - liblapack-dev
      - python3-matplotlib
      # - python-numpy
      # - python-scipy
      # - python-matplotlib
      # - python3-pip
      # - python3-numpy
      # - python3-scipy
install:
  - source tests/travis_install.sh
  - pip install --upgrade pip
  - pip install -r requirements.txt
before_script:
  - git config --global user.email "travis.nlpia@totalgood.com"
  - git config --global user.name "nlpia Travis tests"
script:
  - python setup.py test
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache:
  - apt
