language: python
python:
  - "2.7"
env:
  - PACKAGES="django==1.8 django-polymorphic<1.3 django-polymorphic-tree<1.5"
  - PACKAGES="django==1.11"
before_install:
  - pip install -q $PACKAGES
install:
  - pip install -r test_requirements.txt
script:
  - python setup.py test
