# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-10 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_geo_db', '0007_auto_20180310_0603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationmaptype',
            options={'ordering': ('type',)},
        ),
        migrations.AddField(
            model_name='locationmap',
            name='map_file_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationmaptype',
            name='type',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.RemoveField(
            model_name='locationmap',
            name='file',
        ),
        migrations.AlterUniqueTogether(
            name='locationmap',
            unique_together=set([('type', 'location')]),
        ),
    ]
