language: python
python: '3.6'
install:
- pip install tox pbr
script:
- tox
deploy:
  provider: pypi
  user:
    secure: TXy96Jq8M+KJf4d9vd9tkRsg+56wR3ugH+N8nyfBqxCd6XI0D/1SHJVr659n4nBTWr9nMrQAay/V31fbwjZ1xJEFB03ID6RKy03LUdAqsyU+681jY1VOdP1mkyVnUtpWTc+LTHTmVsv3yMlJ1s47Pj70aR7bcHrABvQ6TUN4adlFLmL3LuG2Ty+GDtJwyQ+6hBIhCC8MOZv3Y62YNMuPXPvc5ZdMIqUXel/sJiH9glyEGtVS7ghM2eLMKQd1sEKbndt82AmZZyKgyZ/Hjs5Y7Tq3IsuydsGtVVkXOfMP9Ps12L+VrnHaI07l8yvao/MRVXDX1L9cTdahH/g0JoOjfHIyjWiYz89TZ8pMhTFZJiV2FrIz9phAHGXMPis++n/49Bo+JMNbOh12pO6kyIBme0NUELKKp6dyJV68iG7be7W9xX6aAdlkc+/qqW/ZJ6FfPreWsm0EwtJ1mv4SewYkOyLIFdRrvKT+acaI9lycEk013Sfdl0TjXcFqMuNPSFSzLzZCmN70KtZ7b3YGdFhrko4OP408uIbaxh8Pk+8u/nmWGRxVx8QBmGR67CD5SAAm0rvZ86AAab8e+SXP5liychGt3HJh8adj8X9T62Soj743au0QnVJoCKXajjd3hGtrqKd2EqGp1hrkviMnhtA4UllDxUHl+sC6gOJgN17GQfc=
  password:
    secure: Ss+aPrsx3uL5buIqmSVDeOLHtS/PY74hReRhaVS0NYuF2JypXaRjkxs9ufWm0fIv5uv9L47dd/bCmpk/MAPAhhKxU4uhEtOkxgRXEO9bCwEJWw/RCkGAMnk+XpBsNylOXGBWCAntBP0fi/HK5WA1KVnzvFyauV5ZC0BIs2vRTHt54DRBQf17L/2IhOSbonJzkeJrtvcdOnVKTgkcNESsIgf859kDznHmjwvplu24VVSfVjIhV3v72uZzVkQNShwZVMfAxDD08kvr6HAS49Q7e5xnrKxqbw0OJIOK8A2d/IPb7ebbOH6O6StBdzeNqJFiD7YJN/wbemZQZEMkKuKDVk3HVqVLHO7eYpqBjKwBKsDglMc1ZxahNuj+jyHnKYnoCglZehKUWb95w5ejFjxl2K0osVWqq9MdokLoet9gA+uLXfnDGMeJcxKze973nhJU8xpIJ7xS0Tf+ffaTlb1OC6xFTq76Tb6OMOp6y1OFMD9Iy2aNQSFp6K3qNo4WKrNixubv7Ipl/G59WrvvQKbajYi0QBaX4EHnfZyCPOSKFEcWLeRM+TBI1QsD2S81RuPdZoICRMEFRvp0jWTS4RVJDWHfeHr/C07cGm/477oAmwQx4g5ESUeLwkFz7HrLliTnK17Z2d/ELd0OvFYFBPoWajjclt6ynVJGhLiZg6wipeY=
  on:
    branch: master
    tags: true
