---

ansigenome_info:
  galaxy_url: 'https://galaxy.ansible.com/debops/sysctl'
  github_url: 'https://github.com/debops/ansible-sysctl'
  git_branch: 'master'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

    - name:  'Robin Schneider'
      email: 'ypid@riseup.net'
      github: 'ypid'

  synopsis: |
    The `debops.sysctl` Ansible role manages Linux kernel parameters.
    It comes with kernel hardening and shared memory optimization enabled by
    default.
    The kernel hardening is ported from
    [hardening.os-hardening](https://github.com/hardening-io/ansible-os-hardening)
    for optimal compatibility with DebOps.
