database:
    type: gs
    apiKey: AIzaSyCLQbp5X2B4SWzBw-sz9rUnGHNSdMl0Yx8
    authDomain: "studio-ed756.firebaseapp.com"
    bucket: "studioml-meta"

    guest: true
    use_email_auth: false
    projectId: studio-ed756


storage:
    type: gcloud
    bucket: studio-ed756.appspot.com

   
verbose: debug


