# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buda/entities/signup.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buda.entities import uuid_pb2 as buda_dot_entities_dot_uuid__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='buda/entities/signup.proto',
  package='buda',
  syntax='proto3',
  serialized_pb=_b('\n\x1a\x62uda/entities/signup.proto\x12\x04\x62uda\x1a\x18\x62uda/entities/uuid.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x01\n\x06Signup\x12\x16\n\x02id\x18\x01 \x01(\x0b\x32\n.buda.Uuid\x12\x1b\n\x07user_id\x18\x02 \x01(\x0b\x32\n.buda.Uuid\x12\x1e\n\nvisitor_id\x18\x03 \x01(\x0b\x32\n.buda.Uuid\x12%\n\x11legacy_visitor_id\x18\x64 \x01(\x0b\x32\n.buda.Uuid\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')
  ,
  dependencies=[buda_dot_entities_dot_uuid__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_SIGNUP = _descriptor.Descriptor(
  name='Signup',
  full_name='buda.Signup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='buda.Signup.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='buda.Signup.user_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='visitor_id', full_name='buda.Signup.visitor_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='legacy_visitor_id', full_name='buda.Signup.legacy_visitor_id', index=3,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='buda.Signup.created_at', index=4,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=276,
)

_SIGNUP.fields_by_name['id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SIGNUP.fields_by_name['user_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SIGNUP.fields_by_name['visitor_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SIGNUP.fields_by_name['legacy_visitor_id'].message_type = buda_dot_entities_dot_uuid__pb2._UUID
_SIGNUP.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Signup'] = _SIGNUP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Signup = _reflection.GeneratedProtocolMessageType('Signup', (_message.Message,), dict(
  DESCRIPTOR = _SIGNUP,
  __module__ = 'buda.entities.signup_pb2'
  # @@protoc_insertion_point(class_scope:buda.Signup)
  ))
_sym_db.RegisterMessage(Signup)


# @@protoc_insertion_point(module_scope)
