# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_svg', '0002_auto_20161017_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svgimage',
            name='background_size',
        ),
        migrations.AddField(
            model_name='svgimage',
            name='alignment',
            field=models.CharField(blank=True, choices=[('left', 'left'), ('right', 'right'), ('center', 'center')], max_length=10, null=True, verbose_name='image alignment'),
        ),
        migrations.AddField(
            model_name='svgimage',
            name='caption_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='caption text'),
        ),
        migrations.AddField(
            model_name='svgimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='svgimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='svgimage',
            name='tag_type',
            field=models.CharField(choices=[('div', 'div')], default='div', max_length=50, verbose_name='tag Type'),
        ),
    ]
