gitlab-host: https://git-classes.mst.edu/
gitlab-token: xxxxxxxxxxxxxxxx
namespace: 2016-Fall-CS1001
semester: 2016-FS
# optional; for canvas integration
canvas-token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
canvas-host: mst.instructure.com
# we recommend using one of the import commands to automatically populate the roster
roster:
- name: Smith, John
  section: A
  username: abc123
- name: Smith, Jane
  section: A
  username: xyz123
