# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMain.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName("frmMain")
        frmMain.setWindowModality(QtCore.Qt.NonModal)
        frmMain.resize(640, 480)
        frmMain.setMinimumSize(QtCore.QSize(640, 480))
        frmMain.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setPointSize(10)
        frmMain.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../qet/dev/ico/mac_icon/qelectrotech.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmMain.setWindowIcon(icon)
        self.tabActions = QtWidgets.QTabWidget(frmMain)
        self.tabActions.setGeometry(QtCore.QRect(20, 10, 600, 431))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabActions.setFont(font)
        self.tabActions.setAcceptDrops(False)
        self.tabActions.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabActions.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabActions.setElideMode(QtCore.Qt.ElideLeft)
        self.tabActions.setUsesScrollButtons(False)
        self.tabActions.setTabsClosable(False)
        self.tabActions.setMovable(False)
        self.tabActions.setObjectName("tabActions")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.btnCreate = QtWidgets.QPushButton(self.widget)
        self.btnCreate.setGeometry(QtCore.QRect(10, 300, 261, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCreate.sizePolicy().hasHeightForWidth())
        self.btnCreate.setSizePolicy(sizePolicy)
        self.btnCreate.setObjectName("btnCreate")
        self.lblDataPath_4 = QtWidgets.QLabel(self.widget)
        self.lblDataPath_4.setGeometry(QtCore.QRect(10, 20, 331, 16))
        self.lblDataPath_4.setObjectName("lblDataPath_4")
        self.btn_choose_project = QtWidgets.QPushButton(self.widget)
        self.btn_choose_project.setGeometry(QtCore.QRect(540, 40, 41, 22))
        self.btn_choose_project.setObjectName("btn_choose_project")
        self.txt_project_path = QtWidgets.QLineEdit(self.widget)
        self.txt_project_path.setGeometry(QtCore.QRect(10, 40, 521, 22))
        self.txt_project_path.setObjectName("txt_project_path")
        self.lblDataPath_5 = QtWidgets.QLabel(self.widget)
        self.lblDataPath_5.setGeometry(QtCore.QRect(10, 70, 331, 16))
        self.lblDataPath_5.setObjectName("lblDataPath_5")
        self.lst_recent = QtWidgets.QListWidget(self.widget)
        self.lst_recent.setGeometry(QtCore.QRect(10, 90, 571, 161))
        self.lst_recent.setObjectName("lst_recent")
        self.lbl_info = QtWidgets.QLabel(self.widget)
        self.lbl_info.setGeometry(QtCore.QRect(10, 250, 571, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_info.setFont(font)
        self.lbl_info.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_info.setObjectName("lbl_info")
        self.txtFromPage = QtWidgets.QLineEdit(self.widget)
        self.txtFromPage.setGeometry(QtCore.QRect(300, 270, 41, 22))
        self.txtFromPage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtFromPage.setObjectName("txtFromPage")
        self.lblSize_h_3 = QtWidgets.QLabel(self.widget)
        self.lblSize_h_3.setGeometry(QtCore.QRect(160, 270, 131, 31))
        self.lblSize_h_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSize_h_3.setObjectName("lblSize_h_3")
        self.lblSize_h_4 = QtWidgets.QLabel(self.widget)
        self.lblSize_h_4.setGeometry(QtCore.QRect(350, 270, 21, 31))
        self.lblSize_h_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSize_h_4.setObjectName("lblSize_h_4")
        self.txtToPage = QtWidgets.QLineEdit(self.widget)
        self.txtToPage.setGeometry(QtCore.QRect(380, 270, 41, 22))
        self.txtToPage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtToPage.setObjectName("txtToPage")
        self.chkReservation = QtWidgets.QCheckBox(self.widget)
        self.chkReservation.setGeometry(QtCore.QRect(10, 340, 271, 20))
        self.chkReservation.setObjectName("chkReservation")
        self.btnCreateCn = QtWidgets.QPushButton(self.widget)
        self.btnCreateCn.setGeometry(QtCore.QRect(330, 300, 241, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCreateCn.sizePolicy().hasHeightForWidth())
        self.btnCreateCn.setSizePolicy(sizePolicy)
        self.btnCreateCn.setObjectName("btnCreateCn")
        self.chkImplicit = QtWidgets.QCheckBox(self.widget)
        self.chkImplicit.setGeometry(QtCore.QRect(10, 360, 241, 20))
        self.chkImplicit.setObjectName("chkImplicit")
        self.chkXref = QtWidgets.QCheckBox(self.widget)
        self.chkXref.setGeometry(QtCore.QRect(10, 380, 241, 20))
        self.chkXref.setObjectName("chkXref")
        self.tabActions.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lblDataPath = QtWidgets.QLabel(self.tab_2)
        self.lblDataPath.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.lblDataPath.setObjectName("lblDataPath")
        self.btnDataPath = QtWidgets.QPushButton(self.tab_2)
        self.btnDataPath.setGeometry(QtCore.QRect(550, 30, 41, 22))
        self.btnDataPath.setObjectName("btnDataPath")
        self.txtDataPath = QtWidgets.QLineEdit(self.tab_2)
        self.txtDataPath.setGeometry(QtCore.QRect(10, 30, 531, 22))
        self.txtDataPath.setObjectName("txtDataPath")
        self.lblMax = QtWidgets.QLabel(self.tab_2)
        self.lblMax.setGeometry(QtCore.QRect(10, 330, 271, 16))
        self.lblMax.setObjectName("lblMax")
        self.sldMaxPage = QtWidgets.QSlider(self.tab_2)
        self.sldMaxPage.setGeometry(QtCore.QRect(290, 330, 211, 21))
        self.sldMaxPage.setMinimum(1)
        self.sldMaxPage.setMaximum(100)
        self.sldMaxPage.setOrientation(QtCore.Qt.Horizontal)
        self.sldMaxPage.setInvertedControls(False)
        self.sldMaxPage.setObjectName("sldMaxPage")
        self.txtMaxPage = QtWidgets.QLineEdit(self.tab_2)
        self.txtMaxPage.setGeometry(QtCore.QRect(510, 330, 81, 22))
        self.txtMaxPage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtMaxPage.setObjectName("txtMaxPage")
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setGeometry(QtCore.QRect(40, 143, 61, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setGeometry(QtCore.QRect(40, 243, 61, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setGeometry(QtCore.QRect(100, 163, 21, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.tab_2)
        self.line_4.setGeometry(QtCore.QRect(100, 223, 21, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.tab_2)
        self.line_5.setGeometry(QtCore.QRect(120, 143, 161, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.tab_2)
        self.line_6.setGeometry(QtCore.QRect(30, 150, 20, 101))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.tab_2)
        self.line_7.setGeometry(QtCore.QRect(92, 150, 20, 101))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.tab_2)
        self.line_8.setGeometry(QtCore.QRect(110, 150, 20, 101))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.tab_2)
        self.line_9.setGeometry(QtCore.QRect(130, 150, 20, 101))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.tab_2)
        self.line_10.setGeometry(QtCore.QRect(150, 150, 20, 101))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.tab_2)
        self.line_11.setGeometry(QtCore.QRect(120, 243, 161, 16))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.tab_2)
        self.line_12.setGeometry(QtCore.QRect(170, 150, 20, 101))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.tab_2)
        self.line_13.setGeometry(QtCore.QRect(190, 150, 20, 101))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.tab_2)
        self.line_14.setGeometry(QtCore.QRect(210, 150, 20, 101))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.tab_2)
        self.line_15.setGeometry(QtCore.QRect(230, 150, 20, 101))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.tab_2)
        self.line_16.setGeometry(QtCore.QRect(270, 150, 20, 101))
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_17 = QtWidgets.QFrame(self.tab_2)
        self.line_17.setGeometry(QtCore.QRect(250, 150, 20, 101))
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.line_18 = QtWidgets.QFrame(self.tab_2)
        self.line_18.setGeometry(QtCore.QRect(120, 130, 20, 20))
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_19 = QtWidgets.QFrame(self.tab_2)
        self.line_19.setGeometry(QtCore.QRect(140, 130, 20, 20))
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(self.tab_2)
        self.line_20.setGeometry(QtCore.QRect(180, 130, 20, 20))
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.line_21 = QtWidgets.QFrame(self.tab_2)
        self.line_21.setGeometry(QtCore.QRect(160, 130, 20, 20))
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.line_22 = QtWidgets.QFrame(self.tab_2)
        self.line_22.setGeometry(QtCore.QRect(220, 130, 20, 20))
        self.line_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.line_23 = QtWidgets.QFrame(self.tab_2)
        self.line_23.setGeometry(QtCore.QRect(200, 130, 20, 20))
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.line_25 = QtWidgets.QFrame(self.tab_2)
        self.line_25.setGeometry(QtCore.QRect(240, 130, 20, 20))
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.line_26 = QtWidgets.QFrame(self.tab_2)
        self.line_26.setGeometry(QtCore.QRect(140, 250, 20, 20))
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.line_27 = QtWidgets.QFrame(self.tab_2)
        self.line_27.setGeometry(QtCore.QRect(120, 250, 20, 20))
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.line_28 = QtWidgets.QFrame(self.tab_2)
        self.line_28.setGeometry(QtCore.QRect(180, 250, 20, 20))
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.line_29 = QtWidgets.QFrame(self.tab_2)
        self.line_29.setGeometry(QtCore.QRect(160, 250, 20, 20))
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.line_30 = QtWidgets.QFrame(self.tab_2)
        self.line_30.setGeometry(QtCore.QRect(260, 250, 20, 20))
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.line_31 = QtWidgets.QFrame(self.tab_2)
        self.line_31.setGeometry(QtCore.QRect(240, 250, 20, 20))
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.line_32 = QtWidgets.QFrame(self.tab_2)
        self.line_32.setGeometry(QtCore.QRect(200, 250, 20, 20))
        self.line_32.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.line_33 = QtWidgets.QFrame(self.tab_2)
        self.line_33.setGeometry(QtCore.QRect(220, 250, 20, 20))
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.lblSize_1 = QtWidgets.QLabel(self.tab_2)
        self.lblSize_1.setGeometry(QtCore.QRect(30, 180, 9, 15))
        self.lblSize_1.setObjectName("lblSize_1")
        self.lblSize_2 = QtWidgets.QLabel(self.tab_2)
        self.lblSize_2.setGeometry(QtCore.QRect(60, 123, 13, 15))
        self.lblSize_2.setObjectName("lblSize_2")
        self.lblSize_3 = QtWidgets.QLabel(self.tab_2)
        self.lblSize_3.setGeometry(QtCore.QRect(100, 123, 19, 15))
        self.lblSize_3.setObjectName("lblSize_3")
        self.lblSize_4 = QtWidgets.QLabel(self.tab_2)
        self.lblSize_4.setGeometry(QtCore.QRect(262, 123, 19, 15))
        self.lblSize_4.setObjectName("lblSize_4")
        self.lblSize_5 = QtWidgets.QLabel(self.tab_2)
        self.lblSize_5.setGeometry(QtCore.QRect(103, 180, 19, 15))
        self.lblSize_5.setObjectName("lblSize_5")
        self.lblSize_h = QtWidgets.QLabel(self.tab_2)
        self.lblSize_h.setGeometry(QtCore.QRect(381, 120, 161, 31))
        self.lblSize_h.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSize_h.setObjectName("lblSize_h")
        self.txtSize_h = QtWidgets.QLineEdit(self.tab_2)
        self.txtSize_h.setGeometry(QtCore.QRect(550, 126, 41, 22))
        self.txtSize_h.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtSize_h.setObjectName("txtSize_h")
        self.txtSize_w = QtWidgets.QLineEdit(self.tab_2)
        self.txtSize_w.setGeometry(QtCore.QRect(549, 162, 41, 22))
        self.txtSize_w.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtSize_w.setObjectName("txtSize_w")
        self.lblSize_w = QtWidgets.QLabel(self.tab_2)
        self.lblSize_w.setGeometry(QtCore.QRect(380, 156, 161, 31))
        self.lblSize_w.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSize_w.setObjectName("lblSize_w")
        self.lblSize_h1 = QtWidgets.QLabel(self.tab_2)
        self.lblSize_h1.setGeometry(QtCore.QRect(381, 190, 161, 31))
        self.lblSize_h1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSize_h1.setObjectName("lblSize_h1")
        self.txtSize_h1 = QtWidgets.QLineEdit(self.tab_2)
        self.txtSize_h1.setGeometry(QtCore.QRect(550, 196, 41, 22))
        self.txtSize_h1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtSize_h1.setObjectName("txtSize_h1")
        self.txtSize_w1 = QtWidgets.QLineEdit(self.tab_2)
        self.txtSize_w1.setGeometry(QtCore.QRect(549, 232, 41, 22))
        self.txtSize_w1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtSize_w1.setObjectName("txtSize_w1")
        self.lblSize_w1 = QtWidgets.QLabel(self.tab_2)
        self.lblSize_w1.setGeometry(QtCore.QRect(380, 226, 161, 31))
        self.lblSize_w1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSize_w1.setObjectName("lblSize_w1")
        self.lblSize_w2 = QtWidgets.QLabel(self.tab_2)
        self.lblSize_w2.setGeometry(QtCore.QRect(351, 260, 191, 31))
        self.lblSize_w2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSize_w2.setObjectName("lblSize_w2")
        self.txtSize_w2 = QtWidgets.QLineEdit(self.tab_2)
        self.txtSize_w2.setGeometry(QtCore.QRect(550, 266, 41, 22))
        self.txtSize_w2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtSize_w2.setObjectName("txtSize_w2")
        self.lblReservation = QtWidgets.QLabel(self.tab_2)
        self.lblReservation.setGeometry(QtCore.QRect(310, 290, 191, 31))
        self.lblReservation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblReservation.setObjectName("lblReservation")
        self.txtRes = QtWidgets.QLineEdit(self.tab_2)
        self.txtRes.setGeometry(QtCore.QRect(510, 296, 81, 22))
        self.txtRes.setObjectName("txtRes")
        self.btnSave = QtWidgets.QPushButton(self.tab_2)
        self.btnSave.setGeometry(QtCore.QRect(10, 370, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSave.setFont(font)
        self.btnSave.setObjectName("btnSave")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(60, 190, 18, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(120, 210, 18, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(140, 210, 18, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(160, 210, 18, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(180, 210, 18, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(260, 210, 18, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(220, 210, 18, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(200, 210, 18, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(240, 210, 18, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.lblSize_h_2 = QtWidgets.QLabel(self.tab_2)
        self.lblSize_h_2.setGeometry(QtCore.QRect(280, 80, 161, 21))
        self.lblSize_h_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSize_h_2.setObjectName("lblSize_h_2")
        self.rad_id = QtWidgets.QRadioButton(self.tab_2)
        self.rad_id.setGeometry(QtCore.QRect(455, 90, 71, 20))
        self.rad_id.setObjectName("rad_id")
        self.rad_number = QtWidgets.QRadioButton(self.tab_2)
        self.rad_number.setGeometry(QtCore.QRect(455, 70, 125, 20))
        self.rad_number.setChecked(True)
        self.rad_number.setObjectName("rad_number")
        self.line_98 = QtWidgets.QFrame(self.tab_2)
        self.line_98.setGeometry(QtCore.QRect(440, 70, 20, 41))
        self.line_98.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_98.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_98.setObjectName("line_98")
        self.lbl_about = QtWidgets.QLabel(self.tab_2)
        self.lbl_about.setGeometry(QtCore.QRect(470, 380, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lbl_about.setFont(font)
        self.lbl_about.setObjectName("lbl_about")
        self.tabActions.addTab(self.tab_2, "")
        self.help = QtWidgets.QWidget()
        self.help.setObjectName("help")
        self.lblDataPath_6 = QtWidgets.QLabel(self.help)
        self.lblDataPath_6.setGeometry(QtCore.QRect(10, 20, 581, 381))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblDataPath_6.setFont(font)
        self.lblDataPath_6.setTextFormat(QtCore.Qt.PlainText)
        self.lblDataPath_6.setScaledContents(False)
        self.lblDataPath_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblDataPath_6.setWordWrap(True)
        self.lblDataPath_6.setObjectName("lblDataPath_6")
        self.tabActions.addTab(self.help, "")
        self.btnClose = QtWidgets.QPushButton(frmMain)
        self.btnClose.setGeometry(QtCore.QRect(540, 450, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnClose.setFont(font)
        self.btnClose.setObjectName("btnClose")

        self.retranslateUi(frmMain)
        self.tabActions.setCurrentIndex(0)
        self.btnClose.clicked.connect(frmMain.salir)
        self.btnDataPath.clicked.connect(frmMain.choosePath)
        self.btnCreate.clicked.connect(frmMain.create_tb)
        self.sldMaxPage.sliderMoved['int'].connect(frmMain.sld_changed)
        self.btnSave.clicked.connect(frmMain.save_config)
        self.lst_recent.itemClicked['QListWidgetItem*'].connect(frmMain.recent_picked)
        self.btn_choose_project.clicked.connect(frmMain.choose_project)
        self.btnCreateCn.clicked.connect(frmMain.create_cn)
        self.chkImplicit.clicked.connect(frmMain.chk_implicit_clicked)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        _translate = QtCore.QCoreApplication.translate
        frmMain.setWindowTitle(_translate("frmMain", "QET Terminal Block Generator"))
        self.btnCreate.setText(_translate("frmMain", "Create Terminals Blocks"))
        self.lblDataPath_4.setText(_translate("frmMain", "Select a QET project or pick one from the list"))
        self.btn_choose_project.setText(_translate("frmMain", "..."))
        self.lblDataPath_5.setText(_translate("frmMain", "Recent projects:"))
        self.lbl_info.setText(_translate("frmMain", "NOTIFICATIONS"))
        self.lblSize_h_3.setText(_translate("frmMain", "Process pages from"))
        self.lblSize_h_4.setText(_translate("frmMain", "to"))
        self.chkReservation.setText(_translate("frmMain", "Create terminals for empty spaces"))
        self.btnCreateCn.setText(_translate("frmMain", "Create Connectors"))
        self.chkImplicit.setText(_translate("frmMain", "Search for implicits connections"))
        self.chkXref.setText(_translate("frmMain", "Show only terminal\'s xref"))
        self.tabActions.setTabText(self.tabActions.indexOf(self.widget), _translate("frmMain", "Terminal block"))
        self.lblDataPath.setText(_translate("frmMain", "QET user collection path"))
        self.btnDataPath.setText(_translate("frmMain", "..."))
        self.lblMax.setText(_translate("frmMain", "Maximum number of terminals per page"))
        self.lblSize_1.setText(_translate("frmMain", "<html><head/><body><p><span style=\" color:#ff0000;\">h</span></p></body></html>"))
        self.lblSize_2.setText(_translate("frmMain", "<html><head/><body><p><span style=\" color:#ff0000;\">w</span></p></body></html>"))
        self.lblSize_3.setText(_translate("frmMain", "<html><head/><body><p><span style=\" color:#ff0000;\">w1</span></p></body></html>"))
        self.lblSize_4.setText(_translate("frmMain", "<html><head/><body><p><span style=\" color:#ff0000;\">w2</span></p></body></html>"))
        self.lblSize_5.setText(_translate("frmMain", "<html><head/><body><p><span style=\" color:#ff0000;\">h1</span></p></body></html>"))
        self.lblSize_h.setText(_translate("frmMain", "Head height pixels (h):"))
        self.lblSize_w.setText(_translate("frmMain", "Head width pixels (w):"))
        self.lblSize_h1.setText(_translate("frmMain", "Union height pixels (h1):"))
        self.lblSize_w1.setText(_translate("frmMain", "Union width pixels (w1):"))
        self.lblSize_w2.setText(_translate("frmMain", "Terminal width pixels (w2):"))
        self.lblReservation.setText(_translate("frmMain", "Terminals reservation label:"))
        self.btnSave.setText(_translate("frmMain", "Save Config"))
        self.label.setText(_translate("frmMain", "X1"))
        self.label_2.setText(_translate("frmMain", "1"))
        self.label_3.setText(_translate("frmMain", "2"))
        self.label_4.setText(_translate("frmMain", "3"))
        self.label_5.setText(_translate("frmMain", "4"))
        self.label_6.setText(_translate("frmMain", "..."))
        self.label_7.setText(_translate("frmMain", "6"))
        self.label_8.setText(_translate("frmMain", "5"))
        self.label_9.setText(_translate("frmMain", "7"))
        self.lblSize_h_2.setText(_translate("frmMain", "Cross-references by:"))
        self.rad_id.setText(_translate("frmMain", "auto"))
        self.rad_number.setText(_translate("frmMain", "default (%f-%l%c)"))
        self.lbl_about.setText(_translate("frmMain", "<html>\n"
"<body>\n"
"Created by\n"
"<a href=\"mailto:raulroda@yahoo.com\">Raul Roda</a>\n"
"</p>\n"
"\n"
"</body>\n"
"</html>\n"
"\n"
""))
        self.tabActions.setTabText(self.tabActions.indexOf(self.tab_2), _translate("frmMain", "Config"))
        self.lblDataPath_6.setText(_translate("frmMain", "TERMINALS STRIP\n"
"\n"
"To make the terminal strip, searches for \'terminal\' elements that have a name like X<num>:<text> (e.g. X1:L1, X1:2, X2:+3,...). There are 2 types of connections to a terminal strip:\n"
"\n"
"* Explicit connections: Are represented by \'terminal\' type elements on the diagram. For every terminal are analyzed the conductors connected. Every conductor implies a reserve in the terminal strip except:\n"
"    - Conductors from a terminal to a NEXT_FOLIO\n"
"    - Conductors from a terminal to another terminal with same name\n"
"* Implicit connectios: Is considered a implicit connection if exists at least one \'terminal\' element for the same conductor number and there several conductor with same number. A conductor is not considered a implicit connection if:\n"
"    - Connected between 2 FOLIO_REPORT elements (e.g. NEXT_FOLIO, PREVIOUS_FOLIO)\n"
"\n"
"CONDUCTORS\n"
"\n"
"There 3 posible elements for pin connector: male, female or male/female. The amount of pins for a connector is determined by the maximun of:\n"
"  - number of pins found (X1:1, X1:2,...)\n"
"  - an integer value especified in the \"designation\" field of any of the pins for the connectos.\n"
"\n"
""))
        self.tabActions.setTabText(self.tabActions.indexOf(self.help), _translate("frmMain", "Help"))
        self.btnClose.setText(_translate("frmMain", "Close"))

