---

ansigenome_info:
  galaxy_url: 'https://galaxy.ansible.com/debops-contrib/x2go_server'
  github_url: 'https://github.com/debops-contrib/ansible-x2go_server'
  git_branch: 'master'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Robin Schneider'
      url: 'http://ypid.de/'
      email: 'ypid@riseup.net'
      twitter: 'ypid'
      github: 'ypid'

  synopsis: |
    The `debops-contrib.x2go_server` role allows you to setup and mange
    [X2Go][] on the server-side.
    X2Go enables you to access a graphical desktop of a computer over a low
    bandwidth (or high bandwidth) connection.

    [X2Go]: http://wiki.x2go.org/
