language: python
sudo: false
python:
  - "3.5"
  - "2.7"
  - "2.6"
  - "pypy"
  - "3.6-dev"
  - "nightly"

# NOTE: nightly = 3.7-dev
# -- TEST-BALLON: Check if Python 3.6 is actually Python 3.5.1 or newer
matrix:
  allow_failures:
    - python: "3.6-dev"
    - python: "nightly"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - travis_retry pip install -q -U pytest
  - python setup.py -q install

script:
  - python --version
  - py.test tests

# -- USE: New container-based infrastructure for faster startup.
#    http://docs.travis-ci.com/user/workers/container-based-infrastructure/
#
# SEE ALSO:
#   http://lint.travis-ci.org
#   http://docs.travis-ci.com/user/caching/
#   http://docs.travis-ci.com/user/multi-os/  (Linux, MACOSX)
