
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-10T15:02:02+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e0a8ff6f942564d2f097dc4da74b0c0bb3232d83",
 "version": "1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
