language: python
sudo: false
python:
 - 3.5
 - 3.6

addons:
  apt:
    packages:
    - slapd
    - ldap-utils

env:
 - DATABASE_URL=postgres://postgres@/spud
 - DATABASE_URL=mysql://root:@localhost/spud
 - DATABASE_URL=sqlite://

install:
# Install database drivers
  - bash -c "if [[ $DATABASE_URL = postgres* ]]; then pip install psycopg2==2.7.3.1; fi; "
  - bash -c "if [[ $DATABASE_URL = mysql* ]]; then pip install mysqlclient==1.3.12; fi; "
# Install other dependancies
  - pip install -rrequirements/tests.txt

script:
  - flake8
  - ./manage.py collectstatic --settings="karaage.tests.settings" -v 2 --noinput
  - python ./manage.py test --settings="karaage.tests.settings" -v 2 karaage.tests
  - ./manage.py collectstatic --settings="karaage.plugins.kgapplications.tests.settings" -v 2 --noinput
  - python ./manage.py test --settings="karaage.plugins.kgapplications.tests.settings" -v 2 karaage.plugins.kgapplications
  - ./manage.py collectstatic --settings="karaage.plugins.kgsoftware.tests.settings" -v 2 --noinput
  - python ./manage.py test --settings="karaage.plugins.kgsoftware.tests.settings" -v 2 karaage.plugins.kgsoftware.tests
  - ./manage.py collectstatic --settings="karaage.plugins.kgsoftware.applications.tests.settings" -v 2 --noinput
  - python ./manage.py test --settings="karaage.plugins.kgsoftware.applications.tests.settings" -v 2 karaage.plugins.kgsoftware
  - ./manage.py collectstatic --settings="karaage.plugins.kgusage.tests.settings" -v 2 --noinput
  - python ./manage.py test --settings="karaage.plugins.kgusage.tests.settings" -v 2 karaage.plugins.kgusage

matrix:
  fast_finish: true
