---

ansigenome_info:
  galaxy_url: 'https://galaxy.ansible.com/debops-contrib/btrfs'
  github_url: 'https://github.com/debops-contrib/ansible-btrfs'
  git_branch: 'master'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Robin Schneider'
      email: 'ypid@riseup.net'
      github: 'ypid'

  synopsis: |
    The `debops-contrib.btrfs` Ansible role allows you manage your Btrfs.
    Currently the role supports management of Btrfs subvolumes.
    More can be implemented as needed.

    Note: Install https://github.com/ypid/ansible-btrfs-subvolume manually for now.
