# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtpad/gui_profile.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(450, 170)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(450, 170))
        Dialog.setMaximumSize(QtCore.QSize(450, 170))
        Dialog.setModal(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.widthBox = QtWidgets.QSpinBox(Dialog)
        self.widthBox.setMaximum(9999)
        self.widthBox.setSingleStep(25)
        self.widthBox.setObjectName("widthBox")
        self.gridLayout.addWidget(self.widthBox, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.backgroundButton = QtWidgets.QToolButton(Dialog)
        self.backgroundButton.setObjectName("backgroundButton")
        self.gridLayout.addWidget(self.backgroundButton, 0, 6, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.heightBox = QtWidgets.QSpinBox(Dialog)
        self.heightBox.setMaximum(9999)
        self.heightBox.setSingleStep(25)
        self.heightBox.setObjectName("heightBox")
        self.gridLayout.addWidget(self.heightBox, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.fontColorButton = QtWidgets.QToolButton(Dialog)
        self.fontColorButton.setObjectName("fontColorButton")
        self.gridLayout.addWidget(self.fontColorButton, 1, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.fontSizeBox = QtWidgets.QSpinBox(Dialog)
        self.fontSizeBox.setObjectName("fontSizeBox")
        self.gridLayout.addWidget(self.fontSizeBox, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 3, 1, 1)
        self.fontFamilyCombo = QtWidgets.QFontComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontFamilyCombo.sizePolicy().hasHeightForWidth())
        self.fontFamilyCombo.setSizePolicy(sizePolicy)
        self.fontFamilyCombo.setMaximumSize(QtCore.QSize(150, 16777215))
        self.fontFamilyCombo.setObjectName("fontFamilyCombo")
        self.gridLayout.addWidget(self.fontFamilyCombo, 2, 4, 1, 3)
        self.backgroundLabel = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backgroundLabel.sizePolicy().hasHeightForWidth())
        self.backgroundLabel.setSizePolicy(sizePolicy)
        self.backgroundLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.gridLayout.addWidget(self.backgroundLabel, 0, 4, 1, 1)
        self.fontColorLabel = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontColorLabel.sizePolicy().hasHeightForWidth())
        self.fontColorLabel.setSizePolicy(sizePolicy)
        self.fontColorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fontColorLabel.setObjectName("fontColorLabel")
        self.gridLayout.addWidget(self.fontColorLabel, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 5, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.allBox = QtWidgets.QCheckBox(Dialog)
        self.allBox.setObjectName("allBox")
        self.horizontalLayout.addWidget(self.allBox)
        self.defaultBox = QtWidgets.QCheckBox(Dialog)
        self.defaultBox.setObjectName("defaultBox")
        self.horizontalLayout.addWidget(self.defaultBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Default appearance"))
        self.label.setText(_translate("Dialog", "Width"))
        self.label_3.setText(_translate("Dialog", "Background color"))
        self.backgroundButton.setText(_translate("Dialog", "..."))
        self.label_2.setText(_translate("Dialog", "Height"))
        self.label_4.setText(_translate("Dialog", "Font color"))
        self.fontColorButton.setText(_translate("Dialog", "..."))
        self.label_5.setText(_translate("Dialog", "Font size"))
        self.label_6.setText(_translate("Dialog", "Font family"))
        self.backgroundLabel.setText(_translate("Dialog", "#FFFFFF"))
        self.fontColorLabel.setText(_translate("Dialog", "#000000"))
        self.allBox.setText(_translate("Dialog", "Apply to all"))
        self.defaultBox.setText(_translate("Dialog", "Set as default"))

