# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtpad/gui_preferences.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(530, 260)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.listWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayout.addWidget(self.listWidget, 0, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 3)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.hotkeysBox = QtWidgets.QCheckBox(self.page)
        self.hotkeysBox.setObjectName("hotkeysBox")
        self.gridLayout_3.addWidget(self.hotkeysBox, 1, 0, 1, 1)
        self.minimizeBox = QtWidgets.QCheckBox(self.page)
        self.minimizeBox.setObjectName("minimizeBox")
        self.gridLayout_3.addWidget(self.minimizeBox, 0, 0, 1, 1)
        self.safeDeleteBox = QtWidgets.QCheckBox(self.page)
        self.safeDeleteBox.setObjectName("safeDeleteBox")
        self.gridLayout_3.addWidget(self.safeDeleteBox, 3, 0, 1, 1)
        self.deleteEmptyNotesBox = QtWidgets.QCheckBox(self.page)
        self.deleteEmptyNotesBox.setObjectName("deleteEmptyNotesBox")
        self.gridLayout_3.addWidget(self.deleteEmptyNotesBox, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 4, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setMaximumSize(QtCore.QSize(135, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.leftClickCombo = QtWidgets.QComboBox(self.page_2)
        self.leftClickCombo.setObjectName("leftClickCombo")
        self.gridLayout_4.addWidget(self.leftClickCombo, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 3, 0, 1, 1)
        self.middleClickCombo = QtWidgets.QComboBox(self.page_2)
        self.middleClickCombo.setObjectName("middleClickCombo")
        self.gridLayout_4.addWidget(self.middleClickCombo, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 6, 0, 1, 1)
        self.startupCombo = QtWidgets.QComboBox(self.page_2)
        self.startupCombo.setObjectName("startupCombo")
        self.gridLayout_4.addWidget(self.startupCombo, 6, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 94, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 8, 0, 1, 1)
        self.cmdStartupLabel = QtWidgets.QLabel(self.page_2)
        self.cmdStartupLabel.setObjectName("cmdStartupLabel")
        self.gridLayout_4.addWidget(self.cmdStartupLabel, 7, 0, 1, 1)
        self.cmdLeftLabel = QtWidgets.QLabel(self.page_2)
        self.cmdLeftLabel.setObjectName("cmdLeftLabel")
        self.gridLayout_4.addWidget(self.cmdLeftLabel, 1, 0, 1, 1)
        self.cmdMiddleText = QtWidgets.QLineEdit(self.page_2)
        self.cmdMiddleText.setObjectName("cmdMiddleText")
        self.gridLayout_4.addWidget(self.cmdMiddleText, 4, 1, 1, 1)
        self.cmdLeftText = QtWidgets.QLineEdit(self.page_2)
        self.cmdLeftText.setObjectName("cmdLeftText")
        self.gridLayout_4.addWidget(self.cmdLeftText, 1, 1, 1, 1)
        self.cmdMiddleLabel = QtWidgets.QLabel(self.page_2)
        self.cmdMiddleLabel.setObjectName("cmdMiddleLabel")
        self.gridLayout_4.addWidget(self.cmdMiddleLabel, 4, 0, 1, 1)
        self.cmdStartupText = QtWidgets.QLineEdit(self.page_2)
        self.cmdStartupText.setObjectName("cmdStartupText")
        self.gridLayout_4.addWidget(self.cmdStartupText, 7, 1, 1, 1)
        self.cmdLeftLine = QtWidgets.QFrame(self.page_2)
        self.cmdLeftLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.cmdLeftLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cmdLeftLine.setObjectName("cmdLeftLine")
        self.gridLayout_4.addWidget(self.cmdLeftLine, 2, 0, 1, 2)
        self.cmdMiddleLine = QtWidgets.QFrame(self.page_2)
        self.cmdMiddleLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.cmdMiddleLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cmdMiddleLine.setObjectName("cmdMiddleLine")
        self.gridLayout_4.addWidget(self.cmdMiddleLine, 5, 0, 1, 2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.fetchClearBox = QtWidgets.QCheckBox(self.page_3)
        self.fetchClearBox.setObjectName("fetchClearBox")
        self.gridLayout_5.addWidget(self.fetchClearBox, 4, 0, 1, 1)
        self.fetchTxtBox = QtWidgets.QCheckBox(self.page_3)
        self.fetchTxtBox.setObjectName("fetchTxtBox")
        self.gridLayout_5.addWidget(self.fetchTxtBox, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 6, 0, 1, 1)
        self.fetchFileBox = QtWidgets.QCheckBox(self.page_3)
        self.fetchFileBox.setObjectName("fetchFileBox")
        self.gridLayout_5.addWidget(self.fetchFileBox, 2, 0, 1, 1)
        self.fetchUrlBox = QtWidgets.QCheckBox(self.page_3)
        self.fetchUrlBox.setObjectName("fetchUrlBox")
        self.gridLayout_5.addWidget(self.fetchUrlBox, 1, 0, 1, 1)
        self.fetchIconBox = QtWidgets.QCheckBox(self.page_3)
        self.fetchIconBox.setObjectName("fetchIconBox")
        self.gridLayout_5.addWidget(self.fetchIconBox, 5, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 2, 0, 1, 1)
        self.framelessBox = QtWidgets.QCheckBox(self.page_4)
        self.framelessBox.setObjectName("framelessBox")
        self.gridLayout_6.addWidget(self.framelessBox, 0, 0, 1, 2)
        self.defaultNameTxtText = QtWidgets.QLineEdit(self.page_4)
        self.defaultNameTxtText.setObjectName("defaultNameTxtText")
        self.gridLayout_6.addWidget(self.defaultNameTxtText, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 3, 0, 1, 1)
        self.defaultNameImgText = QtWidgets.QLineEdit(self.page_4)
        self.defaultNameImgText.setObjectName("defaultNameImgText")
        self.gridLayout_6.addWidget(self.defaultNameImgText, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem3, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout.addWidget(self.stackedWidget, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Preferences"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Dialog", "General settings"))
        item = self.listWidget.item(1)
        item.setText(_translate("Dialog", "Default actions"))
        item = self.listWidget.item(2)
        item.setText(_translate("Dialog", "Fetch clipboard"))
        item = self.listWidget.item(3)
        item.setText(_translate("Dialog", "Appearance"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.hotkeysBox.setText(_translate("Dialog", "Enable hotkeys"))
        self.minimizeBox.setText(_translate("Dialog", "Minimize on startup"))
        self.safeDeleteBox.setText(_translate("Dialog", "Confirm before deletion"))
        self.deleteEmptyNotesBox.setText(_translate("Dialog", "Delete empty notes"))
        self.label.setText(_translate("Dialog", "Left click action"))
        self.label_2.setText(_translate("Dialog", "Middle click action"))
        self.label_3.setText(_translate("Dialog", "Startup action"))
        self.cmdStartupLabel.setText(_translate("Dialog", "Command:"))
        self.cmdLeftLabel.setText(_translate("Dialog", "Command:"))
        self.cmdMiddleLabel.setText(_translate("Dialog", "Command:"))
        self.fetchClearBox.setText(_translate("Dialog", "Clear clipboard after fetch"))
        self.fetchTxtBox.setText(_translate("Dialog", "Fetch text from file (*.txt)"))
        self.fetchFileBox.setText(_translate("Dialog", "Fetch image from file"))
        self.fetchUrlBox.setText(_translate("Dialog", "Fetch image from URL"))
        self.fetchIconBox.setText(_translate("Dialog", "Show fetch icon in context menu"))
        self.label_4.setText(_translate("Dialog", "Default name (text)"))
        self.framelessBox.setText(_translate("Dialog", "Replace native window frame (frameless)"))
        self.label_5.setText(_translate("Dialog", "Default name (image)"))

