image: paternal/pythons

tox:
  script:
    - tox
  coverage: '/^TOTAL.*\s(\d+)\%$/'

pages:
  script:
    - pip3 install -r requirements.txt
    - test -d public || mkdir public
    - python3 -m pypimonitor examples/spalax.yaml > public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
