# -*- coding: utf-8 -*-

_child = [
"24 24 98 2",
"  	c None",
". 	c #FFFFFF",
"+ 	c #FEFEFE",
"@ 	c #F0F0F0",
"# 	c #F8F8F8",
"$ 	c #F3F3F3",
"% 	c #FCFCFC",
"& 	c #E0E0E0",
"* 	c #EEEEEE",
"= 	c #F6F6F6",
"- 	c #F4F4F4",
"; 	c #E2E2E2",
"> 	c #CBCBCB",
", 	c #E4E4E4",
"' 	c #EBEBEB",
") 	c #F2F2F2",
"! 	c #F5F5F5",
"~ 	c #8F8F8F",
"{ 	c #BBBBBB",
"] 	c #DEDEDE",
"^ 	c #CFCFCF",
"/ 	c #D2D2D2",
"( 	c #FDFDFD",
"_ 	c #E8E8E8",
": 	c #F1F1F1",
"< 	c #EFEFEF",
"[ 	c #D7D7D7",
"} 	c #F7F7F7",
"| 	c #F9F9F9",
"1 	c #B6B6B6",
"2 	c #EFEDEC",
"3 	c #EEECEC",
"4 	c #D5D6D5",
"5 	c #CECCCE",
"6 	c #E8E9E9",
"7 	c #ECECEC",
"8 	c #D6D6D6",
"9 	c #B2B2B2",
"0 	c #FCFCFD",
"a 	c #D6D5D8",
"b 	c #FBFBFC",
"c 	c #CACCCA",
"d 	c #AAAAAA",
"e 	c #A9A9A9",
"f 	c #F1F1F2",
"g 	c #EBEBEA",
"h 	c #CCCCCC",
"i 	c #B7B7B7",
"j 	c #BEBEBE",
"k 	c #D0D0D0",
"l 	c #D9D9D9",
"m 	c #E1E1E1",
"n 	c #DDDDDD",
"o 	c #9A9A9A",
"p 	c #7C7C7C",
"q 	c #B4B4B4",
"r 	c #DFDFDF",
"s 	c #959595",
"t 	c #8B8B8B",
"u 	c #BCBCBC",
"v 	c #E7E7E7",
"w 	c #BFBFBF",
"x 	c #909090",
"y 	c #929292",
"z 	c #B0B0B0",
"A 	c #C4C4C4",
"B 	c #949494",
"C 	c #A2A2A2",
"D 	c #B1B1B1",
"E 	c #C9C9C9",
"F 	c #C1C1C1",
"G 	c #A1A1A1",
"H 	c #B8B8B8",
"I 	c #C6C6C6",
"J 	c #8D8D8D",
"K 	c #919191",
"L 	c #C7C7C7",
"M 	c #A3A3A3",
"N 	c #888888",
"O 	c #A8A8A8",
"P 	c #AEAEAE",
"Q 	c #A4A4A4",
"R 	c #D8D8D8",
"S 	c #A6A6A6",
"T 	c #A5A5A5",
"U 	c #979797",
"V 	c #EDEDED",
"W 	c #AFAFAF",
"X 	c #8A8A8A",
"Y 	c #ADADAD",
"Z 	c #FBFBFB",
"` 	c #E9E9E9",
" .	c #C5C5C5",
"..	c #E6E6E6",
"+.	c #D3D3D3",
"@.	c #C0C0C0",
"#.	c #C8C8C8",
"$.	c #FAFAFA",
". . . . . . . . . . . . . . . . . . . . . . . . ",
". . . . . . . . . . . . . . . . . . . . . . . . ",
". . . . . . . . + . . . . . . . . . . . . . . . ",
". . . . . . . @ # + . # $ + % . . . . . . . . . ",
". . . . . . . & * = = = - ; > , ' $ . . . . . . ",
". . . . . . % # ) - - ! @ ~ { ] ^ / ( . . . . . ",
". . . . . _ : ) < - $ - $ [ } | / 1 # . . . . . ",
". . . . . 2 3 4 5 6 ) - ) - $ 7 8 9 . . . . . . ",
". . . . . 0 a b c ; : ) 7 : ; d e ^ . . . . . . ",
". . . . . . . f g @ * @ h i i j k [ ! . . . . . ",
". . . . . . . . l m n o p q r s t u 7 . . . . . ",
". . . . . . . . . ) @ v 7 w x y x z % . . . . . ",
". . . . . . . . . . . . . A B C D E . . . . . . ",
". . . . . . . . . . . . . F B G H I + . . . . . ",
". . . . . . . . . . . . . q J K i L . . . . . . ",
". . . . . . . . . . . . - M s N i h . . . . . . ",
". . . . . . . . . . . . A O y { i / . . . . . . ",
". . . . . . . . . . . = P Q m ^ q R . . . . . . ",
". . . . . . . . . . . * S T | [ U A . . . . . . ",
". . . . . . . . . . . V S W # } X Y Z . . . . . ",
". . . . . . . } @ ` [ H Y P ; / w  ...+ . . . . ",
". . . . . . Z & +./ L w j @.#.j i  .r = . . . . ",
". . . . . . Z } ! = } # $.$.Z % . % . . . . . . ",
". . . . . . . . . . . . . . . . . . . . . . . . "]
