# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20171106_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
