# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20171106_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spenttime',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='task',
            name='developers',
        ),
        migrations.AddField(
            model_name='task',
            name='developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Developer'),
            preserve_default=False,
        ),
    ]
