---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/nodejs"
  github_url: "https://github.com/debops/ansible-nodejs"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    The `debops.nodejs` role will install NodeJS packages, either from the
    current OS release, or from NodeSource.com which provides upstream
    packages. It can be used to install system-wide NPM packages as well.

