---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/cran"
  github_url: "https://github.com/debops/ansible-cran"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    [The Comprehensive R Archive Network](https://cran.r-project.org/) (CRAN) is
    a repository of precompiled packages for the R statistical programming language
    environment. This role can be used to enable the upstream CRAN APT repositories
    and install R packages, both via APT and via R itself.
