
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-03-14T12:07:39-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "15f4a8e1a046c6191f22e46099dad10aafb1fdce",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
