
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-03-09T11:20:02-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea34911190986f85eefdc9aced69fdfbc0a26f51",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
