# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_selection_list_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1049, 770)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.GRP_WORKFLOW = QtWidgets.QGroupBox(self.frame)
        self.GRP_WORKFLOW.setObjectName("GRP_WORKFLOW")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.GRP_WORKFLOW)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BTN_WORKFLOW = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_WORKFLOW.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_WORKFLOW.setMaximumSize(QtCore.QSize(64, 64))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/intermake/dropdown.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_WORKFLOW.setIcon(icon)
        self.BTN_WORKFLOW.setIconSize(QtCore.QSize(32, 32))
        self.BTN_WORKFLOW.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_WORKFLOW.setObjectName("BTN_WORKFLOW")
        self.horizontalLayout_2.addWidget(self.BTN_WORKFLOW)
        self.line_3 = QtWidgets.QFrame(self.GRP_WORKFLOW)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.BTN_CREATE = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_CREATE.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_CREATE.setMaximumSize(QtCore.QSize(64, 64))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/groot/create.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_CREATE.setIcon(icon1)
        self.BTN_CREATE.setIconSize(QtCore.QSize(32, 32))
        self.BTN_CREATE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_CREATE.setObjectName("BTN_CREATE")
        self.horizontalLayout_2.addWidget(self.BTN_CREATE)
        self.BTN_REMOVE = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_REMOVE.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_REMOVE.setMaximumSize(QtCore.QSize(64, 64))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/groot/remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_REMOVE.setIcon(icon2)
        self.BTN_REMOVE.setIconSize(QtCore.QSize(32, 32))
        self.BTN_REMOVE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_REMOVE.setObjectName("BTN_REMOVE")
        self.horizontalLayout_2.addWidget(self.BTN_REMOVE)
        self.BTN_VIEW = QtWidgets.QToolButton(self.GRP_WORKFLOW)
        self.BTN_VIEW.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_VIEW.setMaximumSize(QtCore.QSize(64, 64))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/groot/view.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_VIEW.setIcon(icon3)
        self.BTN_VIEW.setIconSize(QtCore.QSize(32, 32))
        self.BTN_VIEW.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_VIEW.setObjectName("BTN_VIEW")
        self.horizontalLayout_2.addWidget(self.BTN_VIEW)
        self.horizontalLayout.addWidget(self.GRP_WORKFLOW)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BTN_CHANGE_SELECTION = QtWidgets.QToolButton(self.groupBox_2)
        self.BTN_CHANGE_SELECTION.setMinimumSize(QtCore.QSize(192, 64))
        self.BTN_CHANGE_SELECTION.setMaximumSize(QtCore.QSize(192, 64))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/groot/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_CHANGE_SELECTION.setIcon(icon4)
        self.BTN_CHANGE_SELECTION.setIconSize(QtCore.QSize(32, 32))
        self.BTN_CHANGE_SELECTION.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.BTN_CHANGE_SELECTION.setObjectName("BTN_CHANGE_SELECTION")
        self.horizontalLayout_3.addWidget(self.BTN_CHANGE_SELECTION)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)
        self.BTN_REFRESH = QtWidgets.QToolButton(self.groupBox_2)
        self.BTN_REFRESH.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_REFRESH.setMaximumSize(QtCore.QSize(64, 64))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/groot/refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_REFRESH.setIcon(icon5)
        self.BTN_REFRESH.setIconSize(QtCore.QSize(32, 32))
        self.BTN_REFRESH.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_REFRESH.setObjectName("BTN_REFRESH")
        self.horizontalLayout_3.addWidget(self.BTN_REFRESH)
        self.horizontalLayout.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.LBL_ALL = QtWidgets.QLabel(Dialog)
        self.LBL_ALL.setObjectName("LBL_ALL")
        self.gridLayout.addWidget(self.LBL_ALL, 0, 0, 1, 1)
        self.LST_ALL = QtWidgets.QTreeWidget(Dialog)
        self.LST_ALL.setObjectName("LST_ALL")
        self.LST_ALL.headerItem().setText(0, "1")
        self.LST_ALL.header().setVisible(False)
        self.gridLayout.addWidget(self.LST_ALL, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(0, 128, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem1)
        self.BTN_SELECT = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_SELECT.sizePolicy().hasHeightForWidth())
        self.BTN_SELECT.setSizePolicy(sizePolicy)
        self.BTN_SELECT.setIcon(icon1)
        self.BTN_SELECT.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.BTN_SELECT.setObjectName("BTN_SELECT")
        self.verticalLayout_2.addWidget(self.BTN_SELECT)
        self.BTN_DESELECT = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_DESELECT.sizePolicy().hasHeightForWidth())
        self.BTN_DESELECT.setSizePolicy(sizePolicy)
        self.BTN_DESELECT.setIcon(icon2)
        self.BTN_DESELECT.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.BTN_DESELECT.setObjectName("BTN_DESELECT")
        self.verticalLayout_2.addWidget(self.BTN_DESELECT)
        self.BTN_CLEAR = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_CLEAR.sizePolicy().hasHeightForWidth())
        self.BTN_CLEAR.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/groot/select.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_CLEAR.setIcon(icon6)
        self.BTN_CLEAR.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.BTN_CLEAR.setObjectName("BTN_CLEAR")
        self.verticalLayout_2.addWidget(self.BTN_CLEAR)
        spacerItem2 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.LST_SELECTED = QtWidgets.QTreeWidget(Dialog)
        self.LST_SELECTED.setObjectName("LST_SELECTED")
        self.LST_SELECTED.headerItem().setText(0, "1")
        self.LST_SELECTED.header().setVisible(False)
        self.gridLayout.addWidget(self.LST_SELECTED, 1, 2, 1, 1)
        self.LBL_SELECTED = QtWidgets.QLabel(Dialog)
        self.LBL_SELECTED.setObjectName("LBL_SELECTED")
        self.gridLayout.addWidget(self.LBL_SELECTED, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.LBL_NO_DATA_WARNING = QtWidgets.QLabel(Dialog)
        self.LBL_NO_DATA_WARNING.setObjectName("LBL_NO_DATA_WARNING")
        self.verticalLayout.addWidget(self.LBL_NO_DATA_WARNING)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.GRP_WORKFLOW.setTitle(_translate("Dialog", "Workflow"))
        self.BTN_WORKFLOW.setText(_translate("Dialog", "Workflow"))
        self.BTN_CREATE.setText(_translate("Dialog", "Create"))
        self.BTN_REMOVE.setText(_translate("Dialog", "Remove"))
        self.BTN_VIEW.setText(_translate("Dialog", "View"))
        self.groupBox_2.setTitle(_translate("Dialog", "Viewer"))
        self.BTN_CHANGE_SELECTION.setToolTip(_translate("Dialog", "<html><head/><body><p>Switch to edge edit mode.</p></body></html>"))
        self.BTN_CHANGE_SELECTION.setStatusTip(_translate("Dialog", "Remove edge"))
        self.BTN_CHANGE_SELECTION.setText(_translate("Dialog", "Select"))
        self.BTN_REFRESH.setToolTip(_translate("Dialog", "<html><head/><body><p>Switch to edge edit mode.</p></body></html>"))
        self.BTN_REFRESH.setStatusTip(_translate("Dialog", "Remove edge"))
        self.BTN_REFRESH.setText(_translate("Dialog", "Refresh"))
        self.LBL_ALL.setText(_translate("Dialog", "Available"))
        self.BTN_SELECT.setText(_translate("Dialog", "Select"))
        self.BTN_DESELECT.setText(_translate("Dialog", "Deselect"))
        self.BTN_CLEAR.setText(_translate("Dialog", "Clear"))
        self.LBL_SELECTED.setText(_translate("Dialog", "Selected"))
        self.LBL_NO_DATA_WARNING.setText(_translate("Dialog", "<html><head/><body><p>There is no data. Maybe <a href=\"action:view_open_file\">load</a> some data first.</p></body></html>"))
        self.LBL_NO_DATA_WARNING.setProperty("style", _translate("Dialog", "warning"))


