
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cc93aa0fad854678d579a910a90d44618ff6346c",
 "version": "v0.1.1-alpha.post.dev14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
