[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "micropede"
author = "Sci-Bots"
author-email = "info@sci-bots.com"
home-page = "http://sci-bots.com"
license = "BSD-2-Clause"
requires = ["paho-mqtt", "wheezy.routing", "onoff"]
requires-python = ">=3.6"
description-file = "README.md"
