- project:
    name: openstack/python-ironic-inspector-client
    check:
      jobs:
        - openstack-tox-functional
        - python-ironic-inspector-client-tempest-dsvm
    gate:
      jobs:
        - openstack-tox-functional
        - python-ironic-inspector-client-tempest-dsvm
