# Generated by Django 2.0.2 on 2018-02-13 20:03

import almanac.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0005_auto_20180209_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionevent',
            name='description',
            field=almanac.fields.MarkdownField(blank=True, null=True),
        ),
    ]
