---

ansigenome_info:
  galaxy_url: 'https://galaxy.ansible.com/debops-contrib/bitcoind'
  github_url: 'https://github.com/debops-contrib/ansible-bitcoind'
  git_branch: 'master'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:

    - name: 'Robin Schneider'
      email: 'ypid@riseup.net'
      github: 'ypid'

  synopsis: |
    The `debops-contrib.bitcoind` role allows you to manage and configure [bitcoind].
    bitcoind can be used to run a [full node]  in the distributed cryptocurrency network [Bitcoin].
    A full node is a program that fully validates transactions and blocks and
    therefore enforces all of the rules of Bitcoin.

    [Bitcoin]: https://bitcoin.org
    [bitcoind]: https://en.bitcoin.it/wiki/Bitcoind
    [full node]: https://en.bitcoin.it/wiki/Full_node
