runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

# [START handlers]
handlers:

- url: /bootstrap
  static_dir: web/bootstrap
  
- url: /js
  static_dir: web/js

- url: /assets
  static_dir: web/assets

- url: /css
  static_dir: web/css

- url: /images
  static_dir: web/images

- url: /main
  script: scripts.main_page.app

- url: /.*
  script: scripts.main_page.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]

