
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-20T16:07:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c0a64b7b93614d0b275ab1020eb6a484ccc4dd3e",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
