language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_install:
- sudo add-apt-repository ppa:ubuntugis/ppa -y
- sudo apt-get update -qq
- sudo apt-get install libfreetype6-dev
- sudo apt-get install libgeos-dev
install:
# matplotlib 2.1.0 has a bug that causes plotting masked arrays to fail
# https://github.com/matplotlib/matplotlib/issues/9280
- if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then pip install "matplotlib>=1.5.0,!=2.1.0"; fi
- if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then pip install "sphinx>=1.5.0"; fi
- if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then pip install "matplotlib>=1.5.0,!=2.1.0"; fi
- if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then pip install "sphinx>=1.5.0"; fi
- if [[ $TRAVIS_PYTHON_VERSION == "3.5" ]]; then pip install "matplotlib>=1.5.0,!=2.1.0"; fi
- if [[ $TRAVIS_PYTHON_VERSION == "3.5" ]]; then pip install "sphinx>=1.5.0"; fi
- if [[ $TRAVIS_PYTHON_VERSION == "3.6" ]]; then pip install "matplotlib>=1.5.0,!=2.1.0"; fi
- if [[ $TRAVIS_PYTHON_VERSION == "3.6" ]]; then pip install "sphinx>=1.5.0"; fi
- pip install -r requirements.txt
- pip install toolz
- pip install dask
- pip install xarray
- pip install -e ".[pykdtree,quicklook]"
- pip install coveralls
script:
- coverage run --source=pyresample setup.py test && cd docs && mkdir doctest && sphinx-build -E -n -b doctest ./source ./doctest && cd ..
after_success: coveralls
notifications:
  slack: pytroll:96mNSYSI1dBjGyzVXkBT6qFt
