---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/nullmailer"
  github_url: "https://github.com/debops/ansible-nullmailer"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    The [nullmailer](http://untroubled.org/nullmailer/) package can be used to
    setup a forwarding SMTP relay. It does not provide support for local mail, but
    forwards all messages to one or more remote SMTP servers for processing.

    The `debops.nullmailer` role installs and configures the `nullmailer`
    service, optionally with a network access from remote hosts on port 25.

    The role can detect other Mail Transport Agents installed on the managed host,
    and if an MTA from a configurable list is found, the role will automatically
    disable itself to allow easy switch to different SMTP servers.
