- project:
    name: openstack/heat-tempest-plugin
    check:
      jobs:
        - heat-functional-orig-mysql-lbaasv2
        - heat-functional-convg-mysql-lbaasv2
        - heat-functional-convg-mysql-lbaasv2-non-apache
        - heat-functional-convg-mysql-lbaasv2-py35
    gate:
      jobs:
        - heat-functional-orig-mysql-lbaasv2
        - heat-functional-convg-mysql-lbaasv2
        - heat-functional-convg-mysql-lbaasv2-non-apache
        - heat-functional-convg-mysql-lbaasv2-py35
