heat_template_version: queens

description: >
  Memcached service configured with Puppet

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  MemcachedMaxMemory:
    default: '50%'
    description: The maximum amount of memory for memcached to be configured
                 to use when installed. This can be either a percentage ('50%')
                 or a fixed value ('2048').
    type: string
  MonitoringSubscriptionMemcached:
    default: 'overcloud-memcached'
    type: string
  Debug:
    default: false
    description: Set to True to enable debugging on all services.
    type: boolean
  MemcachedDebug:
    default: ''
    description: Set to True to enable debugging Memcached service.
    type: string
    constraints:
      - allowed_values: [ '', 'true', 'True', 'TRUE', 'false', 'False', 'FALSE']

conditions:
  service_debug:
    or:
      - equals: [{get_param: MemcachedDebug}, 'true']
      - equals: [{get_param: MemcachedDebug}, 'True']
      - equals: [{get_param: Debug}, true]

outputs:
  role_data:
    description: Role data for the Memcached role.
    value:
      service_name: memcached
      monitoring_subscription: {get_param: MonitoringSubscriptionMemcached}
      config_settings:
        # NOTE: bind IP is found in Heat replacing the network name with the local node IP
        # for the given network; replacement examples (eg. for internal_api):
        # internal_api -> IP
        # internal_api_uri -> [IP]
        # internal_api_subnet - > IP/CIDR
        memcached::listen_ip: {get_param: [ServiceNetMap, MemcachedNetwork]}
        memcached::max_memory: {get_param: MemcachedMaxMemory}
        memcached::verbosity:
          list_join:
            - ''
            - - 'v'
              - if:
                - service_debug
                - 'v'
                - ''
        tripleo.memcached.firewall_rules:
          '121 memcached':
            dport: 11211
      step_config: |
        include ::tripleo::profile::base::memcached
      service_config_settings:
        collectd:
            tripleo.collectd.plugins.memcached:
              - memcached
            collectd::plugin::memcached::instances:
              local:
                host: "%{hiera('memcached::listen_ip')}"
                port: 11211
