---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-nfs_server"
  galaxy_url: "https://galaxy.ansible.com/debops/nfs_server"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    The `debops.nfs_server` Ansible role can be used to configure a NFS server
    on Debian or Ubuntu hosts.
