---

dependencies: []

galaxy_info:

  company: 'DebOps'
  author: 'Robin Schneider'
  description: 'Manage Linux kernel modules'
  license: 'GPL-3.0'
  min_ansible_version: '2.1.3'

  platforms:

    - name: Debian
      versions:
        - all

    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - system
    - kernel
    - linux
    - modules
