sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install .
  - pip install pytest>=2.7.3 --upgrade
  - pip install coveralls pycodestyle mock

script:
  - pycodestyle amodem/ scripts/
  - echo "Hello World!" | amodem send -vv -l- -o- | amodem recv -vv -l- -i-
  - coverage run --source=amodem --omit="*/__main__.py" -m py.test -vvs

after_success:
  - coverage report
  - coveralls
