sudo: false
dist: trusty

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  # allow failures on CPython dev
  # we want to be warned about these, but they aen't critical
  - "3.7-dev"
matrix:
  allow_failures:
    - python: "3.7-dev"
cache: pip
script:
  - make travis
