
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-22T13:32:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d27fc1d191edb868dae2d70ba06d12da5a6bbe48",
 "version": "0.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
