# Generated by Django 2.0.2 on 2018-02-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BobTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('cdate', models.DateTimeField(verbose_name='date create')),
                ('udate', models.DateTimeField(verbose_name='date create')),
                ('para', models.CharField(max_length=2048)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
