language: c
sudo: false
notifications:
  email:
    - tbekolay@gmail.com

env:
  global:
    - STATIC="false"
    - CONDA_DEPS="jupyter keras matplotlib numpy pillow pytest scipy tensorflow theano"
    - PIP_DEPS=""
    - DOCS="false"

matrix:
  include:
    - env: PYTHON="2.7"
    - env: PYTHON="3.6"
    - env: PYTHON="3.6" STATIC="true"
    - env: PYTHON="3.6" DOCS="true"

# Setup Miniconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME/miniconda"
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test python="$PYTHON" pip
  - source activate test

# Install packages with conda, then pip
install:
  - if [[ "$STATIC" == "true" ]]; then
      export CONDA_DEPS="";
      export PIP_DEPS="flake8 pylint";
    elif [[ "$DOCS" == "true" ]]; then
      export PIP_DEPS="sphinx==1.6.7 ghp-import numpydoc guzzle_sphinx_theme nbsphinx_link";
    fi
  - if [[ -n "$CONDA_DEPS" ]]; then eval conda install --quiet "$CONDA_DEPS"; fi
  - if [[ -n "$PIP_DEPS" ]]; then eval pip install "$PIP_DEPS"; fi
  - export MKL_THREADING_LAYER="GNU"

# Run the tests
script:
  - mkdir -p "$HOME/.ipython/profile_default"
  - "echo 'c.HistoryAccessor.enabled = False\n' > $HOME/.ipython/profile_default/ipython_config.py"
  - if [[ "$STATIC" == "true" ]]; then
      flake8 -v nengo_extras && pylint nengo_extras;
    else
      python setup.py -q develop;
      if [[ "$DOCS" == "true" ]]; then
        if [[ -n "$TRAVIS_TAG" ]]; then
          rm "$HOME/.ipython/profile_default/ipython_config.py";
          sphinx-build -W docs docs/_build;
        fi
      else
        pytest nengo_extras -v --duration 20;
      fi
    fi

after_success:
  - if [[ -n "$TRAVIS_TAG" && "$DOCS" == "true" ]]; then
      export DATE=$(date '+%Y-%m-%d %T');
      git config --global user.email "travis@travis-ci.org";
      git config --global user.name "TravisCI";
      ghp-import -m "Last update at $DATE" -b gh-pages docs/_build;
      git push -fq "https://$GH_TOKEN@github.com/nengo/nengo_extras.git" gh-pages;
    fi
