---

ansigenome_info:
  galaxy_url: "https://galaxy.ansible.com/debops/tcpwrappers"
  github_url: "https://github.com/debops/ansible-tcpwrappers"
  git_branch: "master"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    The `debops.tcpwrappers` Ansible role can be used to manage entries in
    `/etc/hosts.allow` and `/etc/hosts.deny` which are used by TCP Wrappers to
    limit connections to daemons that utilize the `libwrap` library.
