
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: PythonLibrary(BuildFileAddress(src/python/fsqio/pants/buildgen/spindle/BUILD, spindle))

from setuptools import setup

setup(**
{   'classifiers': [   'Intended Audience :: Developers',
                       'License :: OSI Approved :: Apache Software License',
                       'Operating System :: MacOS :: MacOS X',
                       'Operating System :: POSIX :: Linux',
                       'Programming Language :: Python',
                       'Topic :: Software Development :: Build Tools',
                       'Topic :: Software Development :: Testing'],
    'description': 'Pants buildgen for Python projects.',
    'install_requires': [   'pantsbuild.pants>=1.2.0',
                            'fsqio.pants.buildgen.jvm==1.3.1'],
    'license': 'Apache License, Version 2.0',
    'name': 'fsqio.pants.buildgen.spindle',
    'namespace_packages': [   'fsqio',
                              'fsqio.pants',
                              'fsqio.pants.buildgen',
                              'fsqio.pants.buildgen.spindle'],
    'package_data': {   },
    'package_dir': {   '': 'src'},
    'packages': [   'fsqio',
                    'fsqio.pants',
                    'fsqio.pants.buildgen',
                    'fsqio.pants.buildgen.spindle'],
    'url': 'https://github.com/foursquare/fsqio',
    'version': '1.3.1',
    'zip_safe': True}
)
