# Starts up a WAMP router suitable for running the examples in this directory
version: "2"
services:
  crossbar:
    image: crossbario/crossbar:cpy3-17.5.1
    volumes:
      - ./crossbar-config.yaml:/node/.crossbar/config.yaml:ro
    ports:
      - 127.0.0.1:8080:8080
