# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 16:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locale',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together=set([('country', 'code')]),
        ),
    ]
