# Generated by Django 2.0.1 on 2018-01-26 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_auto_20180122_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locale',
            name='data',
        ),
    ]
