# Generated by Django 2.0.1 on 2018-02-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_remove_locale_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='mpoly',
            new_name='outlines',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='poly',
            new_name='bbox',
        ),
    ]
