language: python
python: "2.7"
sudo: required
cache:
  directories:
  - eggs
before_install:
  - sudo apt-get -y install erlang-dev
install:
- python bootstrap.py -v 1.7.1 -c travis-$PLONE_VERSION.cfg
- bin/buildout -N -t 3 -c travis-$PLONE_VERSION.cfg annotate
- bin/buildout -N -t 3 -c travis-$PLONE_VERSION.cfg
script: bin/test
env:
  global:
  - PATH=$PWD/parts/xsltproc/bin:$PWD/parts/rabbitmq/scripts:$PATH
  matrix:
  - PLONE_VERSION=4.x
  - PLONE_VERSION=5.x
